Script permettant de charger les différents fichiers json du site de Stanford  
ainsi que les fichiers csv de kaggle

In [4]:
# Lecture fichiers json (directement sur le site Stanford sans passer par le fichier zip téléchargé)

import io
import json
import zipfile
import requests
import os
import pandas as pd 

URL_CHEXBERT = "https://aimistanforddatasets01.blob.core.windows.net/chexpertplus/chexbert_labels.zip?sv=2019-02-02&sr=b&sig=ASeHnyXUW%2F2Ce5PV3rqKGOeKabbWpIE6Z6zVq1hDke0%3D&st=2026-05-15T15%3A03%3A39Z&se=2026-06-14T15%3A08%3A39Z&sp=r"

try:
    print("Connexion au serveur de Stanford...")
    reponse = requests.get(URL_CHEXBERT, stream=True)
    reponse.raise_for_status()

    # Mise en mémoire du zip
    flux_zip = io.BytesIO(reponse.content)
    
    tous_les_datasets = {}
    tous_les_dataframes = {}

    with zipfile.ZipFile(flux_zip) as archive:
        # Filtre sur les json du zip
        fichiers_json = [f for f in archive.namelist() if f.endswith('.json')]
        
        print(f"\n--- {len(fichiers_json)} fichier(s) JSON détecté(s) dans le ZIP ---")
        
        # Lecture de tous les jsons
        for nom_fichier in fichiers_json:
            print(f"Lecture en cours de : {nom_fichier}...")
            
            with archive.open(nom_fichier) as f:

                json_trav = [json.loads(s.decode('utf-8')) for s in f.readlines()]
                
                tous_les_datasets[nom_fichier] = json_trav

                nom_propre = os.path.basename(nom_fichier).replace('.json', '')
                tous_les_dataframes[nom_propre] = pd.DataFrame(json_trav)

        # Pour chaque json affichage du nombre de lignes et des valeurs de la 1ère ligne
        for nom_fichier, donnees in tous_les_datasets.items():
            print(f"\nFichier : {nom_fichier}")
            print(f"   Nombre de lignes chargées : {len(donnees)}")
            
            if len(donnees) > 0:
                print("   Aperçu du premier élément :")
                print(json.dumps(donnees[0], indent=4, ensure_ascii=False))
            print("-" * 30)

        for nom_df, df in tous_les_dataframes.items():
            print(f"\nDataFrame disponible : '{nom_df}'")
            print(f"   Dimensions : {df.shape[0]} lignes, {df.shape[1]} colonnes.")
            print("   Colonnes disponibles :", list(df.columns))
            print("-" * 40)

except requests.exceptions.HTTPError as e:
    print(f"\nErreur chargement lien : {e}.")
except Exception as e:
    print(f"\nErreur ! : {e}")

Connexion au serveur de Stanford...

--- 3 fichier(s) JSON détecté(s) dans le ZIP ---
Lecture en cours de : report_fixed.json...
Lecture en cours de : impression_fixed.json...
Lecture en cours de : findings_fixed.json...

Fichier : report_fixed.json
   Nombre de lignes chargées : 223462
   Aperçu du premier élément :
{
    "path_to_image": "train/patient42142/study5/view1_frontal.jpg",
    "Enlarged Cardiomediastinum": null,
    "Cardiomegaly": null,
    "Lung Opacity": 0.0,
    "Lung Lesion": null,
    "Edema": null,
    "Consolidation": null,
    "Pneumonia": null,
    "Atelectasis": null,
    "Pneumothorax": 0.0,
    "Pleural Effusion": 0.0,
    "Pleural Other": null,
    "Fracture": null,
    "Support Devices": 1.0,
    "No Finding": null
}
------------------------------

Fichier : impression_fixed.json
   Nombre de lignes chargées : 223462
   Aperçu du premier élément :
{
    "path_to_image": "train/patient42142/study5/view1_frontal.jpg",
    "Enlarged Cardiomediastinum": null,
    "Cardiomegaly": null,
    "Lung Opacity": 0.0,
    "Lung Lesion": null,
    "Edema": null,
    "Consolidation": null,
    "Pneumonia": null,
    "Atelectasis": null,
    "Pneumothorax": 0.0,
    "Pleural Effusion": 0.0,
    "Pleural Other": null,
    "Fracture": null,
    "Support Devices": 1.0,
    "No Finding": null
}
------------------------------

Fichier : findings_fixed.json
   Nombre de lignes chargées : 223462
   Aperçu du premier élément :
{
    "path_to_image": "train/patient42142/study5/view1_frontal.jpg",
    "Enlarged Cardiomediastinum": null,
    "Cardiomegaly": null,
    "Lung Opacity": null,
    "Lung Lesion": null,
    "Edema": null,
    "Consolidation": null,
    "Pneumonia": null,
    "Atelectasis": null,
    "Pneumothorax": null,
    "Pleural Effusion": null,
    "Pleural Other": null,
    "Fracture": null,
    "Support Devices": null,
    "No Finding": 1.0
}
------------------------------

DataFrame disponible : 'report_fixed'
   Dimensions : 223462 lignes, 15 colonnes.
   Colonnes disponibles : ['path_to_image', 'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity', 'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis', 'Pneumothorax', 'Pleural Effusion', 'Pleural Other', 'Fracture', 'Support Devices', 'No Finding']
----------------------------------------

DataFrame disponible : 'impression_fixed'
   Dimensions : 223462 lignes, 15 colonnes.
   Colonnes disponibles : ['path_to_image', 'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity', 'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis', 'Pneumothorax', 'Pleural Effusion', 'Pleural Other', 'Fracture', 'Support Devices', 'No Finding']
----------------------------------------

DataFrame disponible : 'findings_fixed'
   Dimensions : 223462 lignes, 15 colonnes.
   Colonnes disponibles : ['path_to_image', 'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity', 'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis', 'Pneumothorax', 'Pleural Effusion', 'Pleural Other', 'Fracture', 'Support Devices', 'No Finding']
----------------------------------------

In [16]:
import os
import json
import pandas as pd

dossier_json = os.path.join("sources", "chexbert_labels")
fichiers_cibles = ["findings_fixed.json", "report_fixed.json", "impression_fixed.json"]

for fichier in fichiers_cibles:
    chemin_complet = os.path.join(dossier_json, fichier)
    
    nom_variable = f"df_{fichier.replace('.json', '')}"
    
    try:
        if os.path.exists(chemin_complet):
            with open(chemin_complet, 'r', encoding='utf-8') as f:
                donnees_json = [json.loads(ligne) for ligne in f if ligne.strip()]
            
            globals()[nom_variable] = pd.DataFrame(donnees_json)
            
            print(f"[OK] DataFrame '{nom_variable}' créé avec succès.")
            print(f"     Dimensions : {globals()[nom_variable].shape[0]} lignes, {globals()[nom_variable].shape[1]} colonnes.\n")
        else:
            print(f"[Erreur] Le fichier est introuvable : {chemin_complet}")
            
    except Exception as e:
        print(f"[Erreur] Impossible de charger le fichier {fichier} : {e}")

pd.set_option('display.max_columns', None)

display("--- En-tête de df_findings_fixed ---")
display(df_findings_fixed.head(5))

display("--- En-tête de df_report_fixed ---")
display(df_report_fixed.head(5))

display("--- En-tête de df_impression_fixed ---")
display(df_impression_fixed.head(5))

[OK] DataFrame 'df_findings_fixed' créé avec succès.
     Dimensions : 223462 lignes, 15 colonnes.

[OK] DataFrame 'df_report_fixed' créé avec succès.
     Dimensions : 223462 lignes, 15 colonnes.

[OK] DataFrame 'df_impression_fixed' créé avec succès.
     Dimensions : 223462 lignes, 15 colonnes.

'--- En-tête de df_findings_fixed ---'

,path_to_image,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,No Finding
0,train/patient42142/study5/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,train/patient42142/study8/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,train/patient42142/study2/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,train/patient42142/study4/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,train/patient42142/study3/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

'--- En-tête de df_report_fixed ---'

,path_to_image,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,No Finding
0,train/patient42142/study5/view1_frontal.jpg,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.0,NaN
1,train/patient42142/study8/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,1.0,NaN
2,train/patient42142/study2/view1_frontal.jpg,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN
3,train/patient42142/study4/view1_frontal.jpg,NaN,0.0,NaN,NaN,NaN,-1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN
4,train/patient42142/study3/view1_frontal.jpg,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1.0,NaN,0.0,NaN,NaN,1.0,NaN

'--- En-tête de df_impression_fixed ---'

,path_to_image,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,No Finding
0,train/patient42142/study5/view1_frontal.jpg,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.0,NaN
1,train/patient42142/study8/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,1.0,NaN
2,train/patient42142/study2/view1_frontal.jpg,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN
3,train/patient42142/study4/view1_frontal.jpg,NaN,0.0,NaN,NaN,NaN,-1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN
4,train/patient42142/study3/view1_frontal.jpg,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1.0,NaN,0.0,NaN,NaN,1.0,NaN

In [22]:
import os
import pandas as pd

dossier_csv = os.path.join("sources", "kaggle")

chemin_train = os.path.join(dossier_csv, "train.csv")
try:
    if os.path.exists(chemin_train):
        df_train = pd.read_csv(chemin_train)
        display(f"[OK] DataFrame 'df_train' créé avec succès.")
        display(f"Dimensions : {df_train.shape[0]} lignes, {df_train.shape[1]} colonnes.\n")
    else:
        print(f"[Erreur] Le fichier est introuvable : {chemin_train}")
except Exception as e:
    print(f"[Erreur] Impossible de charger train.csv : {e}")

chemin_valid = os.path.join(dossier_csv, "valid.csv")
try:
    if os.path.exists(chemin_valid):
        df_valid = pd.read_csv(chemin_valid)
        display(f"[OK] DataFrame 'df_valid' créé avec succès.")
        display(f"Dimensions : {df_valid.shape[0]} lignes, {df_valid.shape[1]} colonnes.\n")
    else:
        print(f"[Erreur] Le fichier est introuvable : {chemin_valid}")
except Exception as e:
    print(f"[Erreur] Impossible de charger valid.csv : {e}")

display("--- 5 premières lignes de df_train ---")
display(df_train.head(5))
    
display("--- 5 premières lignes de df_valid ---")
display(df_valid.head(5))


df_train_temp = df_train.copy()
df_train_temp['origine'] = 'train'
df_valid_temp = df_valid.copy()
df_valid_temp['origine'] = 'valid'

df_csv_global = pd.concat([df_train_temp, df_valid_temp], axis=0, ignore_index=True)
display(f"[OK] DataFrame 'df_csv_global' créé avec succès.")
display(f"Dimensions : {df_csv_global.shape[0]} lignes, {df_csv_global.shape[1]} colonnes.")
display("--- 5 premières lignes de df_csv_global ---")
display(df_csv_global.head(5))

"[OK] DataFrame 'df_train' créé avec succès."

'Dimensions : 223414 lignes, 19 colonnes.\n'

"[OK] DataFrame 'df_valid' créé avec succès."

'Dimensions : 234 lignes, 19 colonnes.\n'

'--- 5 premières lignes de df_train ---'

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.0
1,CheXpert-v1.0-small/train/patient00002/study2/...,Female,87,Frontal,AP,NaN,NaN,-1.0,1.0,NaN,-1.0,-1.0,NaN,-1.0,NaN,-1.0,NaN,1.0,NaN
2,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Frontal,AP,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Lateral,NaN,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,CheXpert-v1.0-small/train/patient00003/study1/...,Male,41,Frontal,AP,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

'--- 5 premières lignes de df_valid ---'

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,CheXpert-v1.0-small/valid/patient64541/study1/...,Male,73,Frontal,AP,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,CheXpert-v1.0-small/valid/patient64542/study1/...,Male,70,Frontal,PA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,CheXpert-v1.0-small/valid/patient64542/study1/...,Male,70,Lateral,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,CheXpert-v1.0-small/valid/patient64543/study1/...,Male,85,Frontal,AP,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CheXpert-v1.0-small/valid/patient64544/study1/...,Female,42,Frontal,AP,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

"[OK] DataFrame 'df_csv_global' créé avec succès."

'Dimensions : 223648 lignes, 20 colonnes.'

'--- 5 premières lignes de df_csv_global ---'

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,origine
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.0,train
1,CheXpert-v1.0-small/train/patient00002/study2/...,Female,87,Frontal,AP,NaN,NaN,-1.0,1.0,NaN,-1.0,-1.0,NaN,-1.0,NaN,-1.0,NaN,1.0,NaN,train
2,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Frontal,AP,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,train
3,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Lateral,NaN,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,train
4,CheXpert-v1.0-small/train/patient00003/study1/...,Male,41,Frontal,AP,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,train

In [8]:
display (df_train.head(5))

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.0
1,CheXpert-v1.0-small/train/patient00002/study2/...,Female,87,Frontal,AP,NaN,NaN,-1.0,1.0,NaN,-1.0,-1.0,NaN,-1.0,NaN,-1.0,NaN,1.0,NaN
2,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Frontal,AP,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Lateral,NaN,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,CheXpert-v1.0-small/train/patient00003/study1/...,Male,41,Frontal,AP,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [13]:
#Fusion des dataframes csv
colonnes_cibles = [
    'Path', 'Cardiomegaly', 'Atelectasis', 'Consolidation', 'Pleural Other', 
    'Pneumothorax', 'Edema', 'Pneumonia', 'Lung Opacity', 'Enlarged Cardiomediastinum', 
    'Lung Lesion', 'Pleural Effusion', 'Fracture', 'Support Devices', 'No Finding'
]

cols_existantes_train = [c for c in colonnes_cibles if c in df_train.columns]
df_train_filtre = df_train[cols_existantes_train].copy()
df_train_filtre['origine'] = 'train'

cols_existantes_valid = [c for c in colonnes_cibles if c in df_valid.columns]
df_valid_filtre = df_valid[cols_existantes_valid].copy()
df_valid_filtre['origine'] = 'valid'

df_train_et_valid = pd.concat([df_train_filtre, df_valid_filtre], axis=0, ignore_index=True)
        
colonnes_finales = [c for c in colonnes_cibles if c in df_train_et_valid.columns] + ['origine']
df_train_et_valid = df_train_et_valid[colonnes_finales]
        
display (df_train_et_valid.head(5))

,Path,Cardiomegaly,Atelectasis,Consolidation,Pleural Other,Pneumothorax,Edema,Pneumonia,Lung Opacity,Enlarged Cardiomediastinum,Lung Lesion,Pleural Effusion,Fracture,Support Devices,No Finding,origine
0,CheXpert-v1.0-small/train/patient00001/study1/...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,train
1,CheXpert-v1.0-small/train/patient00002/study2/...,-1.0,-1.0,-1.0,NaN,NaN,-1.0,NaN,1.0,NaN,NaN,-1.0,1.0,NaN,NaN,train
2,CheXpert-v1.0-small/train/patient00002/study1/...,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,train
3,CheXpert-v1.0-small/train/patient00002/study1/...,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,train
4,CheXpert-v1.0-small/train/patient00003/study1/...,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,train

In [27]:
#Comparaison json <-> csv

df_findings_fixed.rename(columns={'path_to_image': 'CLE'}, inplace=True)
df_report_fixed.rename(columns={'path_to_image': 'CLE'}, inplace=True)
df_impression_fixed.rename(columns={'path_to_image': 'CLE'}, inplace=True)


donnees_tableau = []

fichiers_json = {
    "df_findings_fixed": df_findings_fixed,
    "df_report_fixed": df_report_fixed,
    "df_impression_fixed": df_impression_fixed
}

for nom_df, df in fichiers_json.items():
    nb_valid = df['CLE'].str.startswith('valid/', na=False).sum()
    nb_train = df['CLE'].str.startswith('train/', na=False).sum()
    nb_total = len(df)
    
    donnees_tableau.append({
        "Nom du DataFrame": nom_df,
        "Lignes 'valid/'": nb_valid,
        "Lignes 'train/'": nb_train,
        "Total Lignes": nb_total
    })

df_resume = pd.DataFrame(donnees_tableau)

print("\n=======================================================")
print("  RÉCAPITULATIF DES LIGNES PAR ORIGINE DANS LES JSON")
print("=======================================================\n")
print(df_resume.to_string(index=False))

df_csv_global['CLE'] = df_csv_global['Path'].astype(str).str.split('small/').str[-1]

nb_valid = df_csv_global['CLE'].str.startswith('valid/', na=False).sum()
nb_train = df_csv_global['CLE'].str.startswith('train/', na=False).sum()
nb_total = len(df_csv_global)

donnees_recap = [{
    "Source": "df_csv_global (colonne CLE)",
    "Lignes 'valid/'": nb_valid,
    "Lignes 'train/'": nb_train,
    "Total lignes": nb_total
}]

df_recap_csv = pd.DataFrame(donnees_recap)

print("\n=======================================================")
print("  RÉCAPITULATIF DES LIGNES PAR ORIGINE DANS LE CSV GLOBAL")
print("=======================================================\n")
print(df_recap_csv.to_string(index=False))

=======================================================
  RÉCAPITULATIF DES LIGNES PAR ORIGINE DANS LES JSON
=======================================================

   Nom du DataFrame  Lignes 'valid/'  Lignes 'train/'  Total Lignes
  df_findings_fixed              234           223228        223462
    df_report_fixed              234           223228        223462
df_impression_fixed              234           223228        223462

=======================================================
  RÉCAPITULATIF DES LIGNES PAR ORIGINE DANS LE CSV GLOBAL
=======================================================

                     Source  Lignes 'valid/'  Lignes 'train/'  Total lignes
df_csv_global (colonne CLE)              234           223414        223648

In [ ]:
# Comparaison clés entre les json et le csv 
cles_csv = set(df_csv_global['CLE'].dropna())

fichiers_json = {
    "df_findings_fixed": df_findings_fixed,
    "df_report_fixed": df_report_fixed,
    "df_impression_fixed": df_impression_fixed
}

for nom_json, df_json in fichiers_json.items():
    
    cles_json = set(df_json['CLE'].dropna())
    
    communes = cles_csv.intersection(cles_json)
    exclusif_csv = cles_csv - cles_json
    exclusif_json = cles_json - cles_csv
    
    donnees_comparatif = [
        {"Vérif": f"Clés uniques dans {nom_json}", "Nombre": len(cles_json)},
        {"Vérif": "Clés uniques dans df_csv_global", "Nombre": len(cles_csv)},
        {"Vérif": "Présentes dans les DEUX (Intersection commune)", "Nombre": len(communes)},
        {"Vérif": f"Présentes dans df_csv_global mais PAS dans {nom_json}", "Nombre": len(exclusif_csv)},
        {"Vérif": f"Présentes dans {nom_json} mais PAS dans df_csv_global", "Nombre": len(exclusif_json)}
    ]
    
    df_tableau_actuel = pd.DataFrame(donnees_comparatif)
    
    print("\n" + "="*70)
    print(f" TABLEAU COMPARATIF : df_csv_global  VS  {nom_json}")
    print("="*70)
    print(df_tableau_actuel.to_string(index=False))
    print("-" * 70)

======================================================================
 TABLEAU COMPARATIF : df_csv_global  VS  df_findings_fixed
======================================================================
                                                       Vérif  Nombre
                         Clés uniques dans df_findings_fixed  223462
                             Clés uniques dans df_csv_global  223648
              Présentes dans les DEUX (Intersection commune)  223462
Présentes dans df_csv_global mais PAS dans df_findings_fixed     186
Présentes dans df_findings_fixed mais PAS dans df_csv_global       0
----------------------------------------------------------------------

======================================================================
 TABLEAU COMPARATIF : df_csv_global  VS  df_report_fixed
======================================================================
                                                     Vérif  Nombre
                         Clés uniques dans df_report_fixed  223462
                           Clés uniques dans df_csv_global  223648
            Présentes dans les DEUX (Intersection commune)  223462
Présentes dans df_csv_global mais PAS dans df_report_fixed     186
Présentes dans df_report_fixed mais PAS dans df_csv_global       0
----------------------------------------------------------------------

======================================================================
 TABLEAU COMPARATIF : df_csv_global  VS  df_impression_fixed
======================================================================
                                                         Vérif  Nombre
                         Clés uniques dans df_impression_fixed  223462
                               Clés uniques dans df_csv_global  223648
                Présentes dans les DEUX (Intersection commune)  223462
Présentes dans df_csv_global mais PAS dans df_impression_fixed     186
Présentes dans df_impression_fixed mais PAS dans df_csv_global       0
----------------------------------------------------------------------

In [30]:
import pandas as pd
import numpy as np

# Dictionnaire de vos 3 DataFrames JSON
fichiers_json = {
    "df_findings_fixed": df_findings_fixed,
    "df_report_fixed": df_report_fixed,
    "df_impression_fixed": df_impression_fixed
}

# Liste des colonnes de pathologie potentielles à comparer (en évitant 'CLE', 'Path', 'origine', etc.)
colonnes_exclues = {'CLE', 'Path', 'origine', 'source_csv', 'report', 'findings', 'impression', 'id'}

for nom_json, df_json in fichiers_json.items():
    
    # 1. Trouver les colonnes de pathologies communes entre ce JSON et le CSV global
    colonnes_communes_patho = list(
        (set(df_csv_global.columns) & set(df_json.columns)) - colonnes_exclues
    )
    
    if not colonnes_communes_patho:
        print(f"\n[Info] Aucune colonne de pathologie commune à comparer pour {nom_json}.")
        continue
        
    # 2. Jointure (Inner Merge) pour ne garder que les clés communes
    # On sélectionne la clé + les colonnes de pathologies à comparer
    df_csv_sub = df_csv_global[['CLE'] + colonnes_communes_patho].dropna(subset=['CLE'])
    df_json_sub = df_json[['CLE'] + colonnes_communes_patho].dropna(subset=['CLE'])
    
    # Suppression des doublons de clés s'il y en a, pour garantir une comparaison 1-pour-1
    df_csv_sub = df_csv_sub.drop_duplicates(subset=['CLE'])
    df_json_sub = df_json_sub.drop_duplicates(subset=['CLE'])
    
    # Fusion sur la clé commune
    df_fusion = pd.merge(df_csv_sub, df_json_sub, on='CLE', suffixes=('_csv', '_json'))
    
    total_cles_communes = len(df_fusion)
    
    if total_cles_communes == 0:
        print(f"\n[Info] Aucune clé en commun entre df_csv_global et {nom_json} pour la comparaison.")
        continue

    # 3. Harmonisation des valeurs pour une comparaison stricte
    # On remplace les NaN par une valeur textuelle fixe et on convertit tout en float/string propre
    for col in colonnes_communes_patho:
        df_fusion[f'{col}_csv'] = df_fusion[f'{col}_csv'].fillna(-2).astype(float)
        df_fusion[f'{col}_json'] = df_fusion[f'{col}_json'].fillna(-2).astype(float)

    # 4. Comparaison ligne par ligne de toutes les colonnes cibles
    # La ligne est identique si TOUTES les colonnes appariées ont la même valeur
    est_identique = np.ones(total_cles_communes, dtype=bool)
    for col in colonnes_communes_patho:
        est_identique &= (df_fusion[f'{col}_csv'] == df_fusion[f'{col}_json'])
    
    nb_identiques = est_identique.sum()
    nb_differents = total_cles_communes - nb_identiques

    # 5. Construction et affichage du tableau récapitulatif pour ce JSON
    donnees_res = [
        {"Métrique sur le contenu des colonnes": "Total des clés communes analysées", "Nombre de clés": total_cles_communes, "Pourcentage": "100.0%"},
        {"Métrique sur le contenu des colonnes": "Clés avec valeurs STRICTEMENT IDENTIQUES", "Nombre de clés": nb_identiques, "Pourcentage": f"{(nb_identiques/total_cles_communes)*100:.2f}%"},
        {"Métrique sur le contenu des colonnes": "Clés avec AU MOINS UNE VALEUR DIFFÉRENTE", "Nombre de clés": nb_differents, "Pourcentage": f"{(nb_differents/total_cles_communes)*100:.2f}%"}
    ]
    
    df_tab_res = pd.DataFrame(donnees_res)
    
    print("\n" + "="*85)
    print(f"ANALYSE DE CONTENU : df_csv_global  VS  {nom_json}")
    print(f"Colonnes médicales comparées ({len(colonnes_communes_patho)}) : {colonnes_communes_patho}")
    print("="*85)
    print(df_tab_res.to_string(index=False))
    print("-" * 85)

=====================================================================================
ANALYSE DE CONTENU : df_csv_global  VS  df_findings_fixed
Colonnes médicales comparées (14) : ['Cardiomegaly', 'Consolidation', 'Atelectasis', 'Pleural Other', 'Pneumothorax', 'Edema', 'Pneumonia', 'Lung Opacity', 'Enlarged Cardiomediastinum', 'Lung Lesion', 'Pleural Effusion', 'Fracture', 'Support Devices', 'No Finding']
=====================================================================================
    Métrique sur le contenu des colonnes  Nombre de clés Pourcentage
       Total des clés communes analysées          223462      100.0%
Clés avec valeurs STRICTEMENT IDENTIQUES            3274       1.47%
Clés avec AU MOINS UNE VALEUR DIFFÉRENTE          220188      98.53%
-------------------------------------------------------------------------------------

=====================================================================================
ANALYSE DE CONTENU : df_csv_global  VS  df_report_fixed
Colonnes médicales comparées (14) : ['Cardiomegaly', 'Consolidation', 'Atelectasis', 'Pleural Other', 'Pneumothorax', 'Edema', 'Pneumonia', 'Lung Opacity', 'Enlarged Cardiomediastinum', 'Lung Lesion', 'Pleural Effusion', 'Fracture', 'Support Devices', 'No Finding']
=====================================================================================
    Métrique sur le contenu des colonnes  Nombre de clés Pourcentage
       Total des clés communes analysées          223462      100.0%
Clés avec valeurs STRICTEMENT IDENTIQUES             500       0.22%
Clés avec AU MOINS UNE VALEUR DIFFÉRENTE          222962      99.78%
-------------------------------------------------------------------------------------

=====================================================================================
ANALYSE DE CONTENU : df_csv_global  VS  df_impression_fixed
Colonnes médicales comparées (14) : ['Cardiomegaly', 'Consolidation', 'Atelectasis', 'Pleural Other', 'Pneumothorax', 'Edema', 'Pneumonia', 'Lung Opacity', 'Enlarged Cardiomediastinum', 'Lung Lesion', 'Pleural Effusion', 'Fracture', 'Support Devices', 'No Finding']
=====================================================================================
    Métrique sur le contenu des colonnes  Nombre de clés Pourcentage
       Total des clés communes analysées          223462      100.0%
Clés avec valeurs STRICTEMENT IDENTIQUES          151559      67.82%
Clés avec AU MOINS UNE VALEUR DIFFÉRENTE           71903      32.18%
-------------------------------------------------------------------------------------

In [31]:
import pandas as pd
import numpy as np

fichiers_json = {
    "df_findings_fixed": df_findings_fixed,
    "df_report_fixed": df_report_fixed,
    "df_impression_fixed": df_impression_fixed
}

colonnes_exclues = {'CLE', 'Path', 'origine', 'source_csv', 'report', 'findings', 'impression', 'id'}

print("="*90)
print("  EXTRACTION DE 5 EXEMPLES DE DIFFÉRENCES POUR VÉRIFICATION MANUELLE")
print("="*90)

for nom_json, df_json in fichiers_json.items():
    
    # 1. Identification des colonnes communes
    colonnes_communes_patho = list((set(df_csv_global.columns) & set(df_json.columns)) - colonnes_exclues)
    
    # 2. Alignement et fusion sur les clés communes
    df_csv_sub = df_csv_global[['CLE'] + colonnes_communes_patho].drop_duplicates(subset=['CLE'])
    df_json_sub = df_json[['CLE'] + colonnes_communes_patho].drop_duplicates(subset=['CLE'])
    df_fusion = pd.merge(df_csv_sub, df_json_sub, on='CLE', suffixes=('_csv', '_json'))
    
    # 3. Remplacement des NaN pour permettre la comparaison effective
    for col in colonnes_communes_patho:
        df_fusion[f'{col}_csv'] = df_fusion[f'{col}_csv'].fillna(-2)
        df_fusion[f'{col}_json'] = df_fusion[f'{col}_json'].fillna(-2)
        
    # 4. Identification des lignes qui ont au moins une différence
    est_identique = np.ones(len(df_fusion), dtype=bool)
    for col in colonnes_communes_patho:
        est_identique &= (df_fusion[f'{col}_csv'] == df_fusion[f'{col}_json'])
        
    # On isole les lignes différentes
    df_differences = df_fusion[~est_identique]
    
    print(f"\n\n»»» Analyse de {nom_json} ({len(df_differences)} lignes différentes au total) «««")
    print("-" * 90)
    
    if df_differences.empty:
        print("Parfait ! Aucune différence trouvée sur ce fichier.")
        continue
        
    # 5. Extraction de 5 exemples (ou moins s'il y en a moins de 5)
    exemples = df_differences.head(5)
    
    for i, (_, ligne) in enumerate(exemples.iterrows(), 1):
        print(f"\nExemple {i} | Clé : {ligne['CLE']}")
        
        # Trouver quelles colonnes précises divergent pour cette ligne
        details_diff = []
        for col in colonnes_communes_patho:
            val_csv = ligne[f'{col}_csv']
            val_json = ligne[f'{col}_json']
            
            if val_csv != val_json:
                # On remet un affichage propre pour les anciens NaN (qui étaient à -2)
                val_csv_txt = "Vide (NaN)" if val_csv == -2 else str(val_csv)
                val_json_txt = "Vide (NaN)" if val_json == -2 else str(val_json)
                
                details_diff.append({
                    "Pathologie": col,
                    "Valeur dans CSV": val_csv_txt,
                    "Valeur dans JSON": val_json_txt
                })
                
        # Affichage des différences de la ligne sous forme de petit tableau
        df_details = pd.DataFrame(details_diff)
        print(df_details.to_string(index=False))
    print("-" * 90)

==========================================================================================
  EXTRACTION DE 5 EXEMPLES DE DIFFÉRENCES POUR VÉRIFICATION MANUELLE
==========================================================================================


»»» Analyse de df_findings_fixed (220188 lignes différentes au total) «««
------------------------------------------------------------------------------------------

Exemple 1 | Clé : train/patient00001/study1/view1_frontal.jpg
      Pathologie Valeur dans CSV Valeur dans JSON
     Atelectasis      Vide (NaN)             -1.0
    Lung Opacity      Vide (NaN)              1.0
Pleural Effusion      Vide (NaN)              0.0
      No Finding             1.0       Vide (NaN)

Exemple 2 | Clé : train/patient00002/study2/view1_frontal.jpg
      Pathologie Valeur dans CSV Valeur dans JSON
    Cardiomegaly            -1.0       Vide (NaN)
   Consolidation            -1.0       Vide (NaN)
     Atelectasis            -1.0       Vide (NaN)
           Edema            -1.0       Vide (NaN)
    Lung Opacity             1.0       Vide (NaN)
Pleural Effusion            -1.0       Vide (NaN)
        Fracture             1.0       Vide (NaN)
      No Finding      Vide (NaN)              1.0

Exemple 3 | Clé : train/patient00002/study1/view1_frontal.jpg
Pathologie Valeur dans CSV Valeur dans JSON
  Fracture             1.0       Vide (NaN)

Exemple 4 | Clé : train/patient00002/study1/view2_lateral.jpg
Pathologie Valeur dans CSV Valeur dans JSON
  Fracture             1.0       Vide (NaN)

Exemple 5 | Clé : train/patient00003/study1/view1_frontal.jpg
                Pathologie Valeur dans CSV Valeur dans JSON
              Cardiomegaly      Vide (NaN)              0.0
Enlarged Cardiomediastinum      Vide (NaN)              0.0
          Pleural Effusion      Vide (NaN)              0.0
           Support Devices      Vide (NaN)              1.0
------------------------------------------------------------------------------------------


»»» Analyse de df_report_fixed (222962 lignes différentes au total) «««
------------------------------------------------------------------------------------------

Exemple 1 | Clé : train/patient00001/study1/view1_frontal.jpg
      Pathologie Valeur dans CSV Valeur dans JSON
    Cardiomegaly      Vide (NaN)              0.0
   Consolidation      Vide (NaN)              0.0
    Pneumothorax             0.0       Vide (NaN)
Pleural Effusion      Vide (NaN)              0.0
 Support Devices             1.0       Vide (NaN)
      No Finding             1.0       Vide (NaN)

Exemple 2 | Clé : train/patient00002/study2/view1_frontal.jpg
      Pathologie Valeur dans CSV Valeur dans JSON
    Cardiomegaly            -1.0              0.0
   Consolidation            -1.0       Vide (NaN)
           Edema            -1.0       Vide (NaN)
       Pneumonia      Vide (NaN)             -1.0
Pleural Effusion            -1.0       Vide (NaN)
        Fracture             1.0       Vide (NaN)

Exemple 3 | Clé : train/patient00002/study1/view1_frontal.jpg
   Pathologie Valeur dans CSV Valeur dans JSON
 Cardiomegaly      Vide (NaN)              0.0
Consolidation            -1.0       Vide (NaN)
  Atelectasis      Vide (NaN)             -1.0
    Pneumonia      Vide (NaN)             -1.0
     Fracture             1.0       Vide (NaN)

Exemple 4 | Clé : train/patient00002/study1/view2_lateral.jpg
                Pathologie Valeur dans CSV Valeur dans JSON
             Consolidation            -1.0       Vide (NaN)
              Pneumothorax      Vide (NaN)              0.0
              Lung Opacity             1.0       Vide (NaN)
Enlarged Cardiomediastinum      Vide (NaN)              0.0
          Pleural Effusion      Vide (NaN)              0.0
                  Fracture             1.0              0.0
                No Finding      Vide (NaN)              1.0

Exemple 5 | Clé : train/patient00003/study1/view1_frontal.jpg
                Pathologie Valeur dans CSV Valeur dans JSON
                     Edema             1.0       Vide (NaN)
              Lung Opacity      Vide (NaN)              1.0
Enlarged Cardiomediastinum      Vide (NaN)             -1.0
------------------------------------------------------------------------------------------


»»» Analyse de df_impression_fixed (71903 lignes différentes au total) «««
------------------------------------------------------------------------------------------

Exemple 1 | Clé : train/patient00002/study2/view1_frontal.jpg
  Pathologie Valeur dans CSV Valeur dans JSON
Cardiomegaly            -1.0              1.0

Exemple 2 | Clé : train/patient00005/study1/view1_frontal.jpg
                Pathologie Valeur dans CSV Valeur dans JSON
Enlarged Cardiomediastinum      Vide (NaN)              1.0

Exemple 3 | Clé : train/patient00005/study1/view2_lateral.jpg
                Pathologie Valeur dans CSV Valeur dans JSON
Enlarged Cardiomediastinum      Vide (NaN)              1.0

Exemple 4 | Clé : train/patient00007/study1/view1_frontal.jpg
  Pathologie Valeur dans CSV Valeur dans JSON
Pneumothorax             1.0              0.0
Lung Opacity             1.0       Vide (NaN)

Exemple 5 | Clé : train/patient00007/study2/view1_frontal.jpg
                Pathologie Valeur dans CSV Valeur dans JSON
Enlarged Cardiomediastinum             1.0       Vide (NaN)
------------------------------------------------------------------------------------------