In [69]:
import pandas as pd
import numpy as np
import random

In [70]:
pd.options.display.max_columns = None

In [71]:
dataset = pd.read_csv("./CheXpert/df_chexpert_plus_240401.csv")
dataset = dataset.sort_values(by="path_to_image", ignore_index=True)
dataset.head()

,path_to_image,path_to_dcm,frontal_lateral,ap_pa,deid_patient_id,patient_report_date_order,report,section_narrative,section_clinical_history,section_history,section_comparison,section_technique,section_procedure_comments,section_findings,section_impression,section_end_of_impression,section_summary,section_accession_number,age,sex,race,ethnicity,interpreter_needed,insurance_type,recent_bmi,deceased,split
0,train/patient00001/study1/view1_frontal.jpg,train/patient00001/study1/view1_frontal.dcm,Frontal,AP,patient00001,1,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\nRADIOGRAPHIC EXAMINATION OF THE CHEST: 3/10/...,"67 years of age, Female, Confirm central line...",NaN,None available.\n \n,NaN,Single view of the chest. \n \n,\n \nLeft subclavian central venous catheter w...,\n \n1. Left subclavian central venous cathet...,NaN,NaN,\n6340977630\nThis report has been anonymized....,68.0,Female,Other,Non-Hispanic/Non-Latino,No,Medicare,44.2,No,train
1,train/patient00002/study1/view1_frontal.jpg,train/patient00002/study1/view1_frontal.dcm,Frontal,AP,patient00002,1,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,"\nFRONTAL AND LATERAL CHEST RADIOGRAPH, TWO VI...",NaN,NaN,\nThere are no prior films available for compa...,NaN,NaN,\nThere is severe kyphosis centered at the mid...,\n1. MARKED KYPHOSIS WITH STATUS POST VERTEBRO...,\n,"4: Possible Significant Abnormality/Change, m...",\n7043874645\nThis report has been anonymized....,87.0,Female,White,Non-Hispanic/Non-Latino,No,Unknown,20.6,Yes,train
2,train/patient00002/study1/view2_lateral.jpg,train/patient00002/study1/view2_lateral.dcm,Lateral,NaN,patient00002,2,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,"\nFRONTAL AND LATERAL CHEST RADIOGRAPH, TWO VI...",NaN,NaN,\nThere are no prior films available for compa...,NaN,NaN,\nThere is severe kyphosis centered at the mid...,\n1. MARKED KYPHOSIS WITH STATUS POST VERTEBRO...,\n,"4: Possible Significant Abnormality/Change, m...",\n6-3-4-0-9-7-7-6-3-0\nThis report has been an...,87.0,Female,White,Non-Hispanic/Non-Latino,No,Unknown,20.6,Yes,train
3,train/patient00002/study2/view1_frontal.jpg,train/patient00002/study2/view1_frontal.dcm,Frontal,AP,patient00002,3,"NARRATIVE:\nSINGLE VIEW OF THE CHEST, 4 VIEWS ...","\nSINGLE VIEW OF THE CHEST, 4 VIEWS LEFT FEMUR...",The patient is an 86 year old trauma to the l...,NaN,NaN,NaN,NaN,NaN,\n1. SINGLE SUPINE PORTABLE FRONTAL VIEW OF TH...,NaN,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI...",\n#8850215333100\nThis report has been anonymi...,87.0,Female,White,Non-Hispanic/Non-Latino,No,Unknown,20.6,Yes,train
4,train/patient00003/study1/view1_frontal.jpg,train/patient00003/study1/view1_frontal.dcm,Frontal,AP,patient00003,1,"NARRATIVE:\nCHEST, ONE VIEW: 2-10-2001\nFINDIN...","\nCHEST, ONE VIEW: 2-10-2001\n",NaN,NaN,NaN,NaN,NaN,"Costophrenic angles sharp, without evidence o...",\n1. NO EVIDENCE OF PNEUMOTHORAX.\n2. MILD INT...,\n,2\nI have personally reviewed the images for ...,\nLFEWOZWVDRX\nThis report has been anonymized...,41.0,Male,White,Non-Hispanic/Non-Latino,Unknown,Private Insurance,NaN,No,train

In [72]:
columns_keep = ['path_to_image', 'deid_patient_id', 'report', 'section_findings', 'section_impression', 'section_summary']
dataset = dataset[columns_keep]
dataset

,path_to_image,deid_patient_id,report,section_findings,section_impression,section_summary
0,train/patient00001/study1/view1_frontal.jpg,patient00001,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\n \nLeft subclavian central venous catheter w...,\n \n1. Left subclavian central venous cathet...,NaN
1,train/patient00002/study1/view1_frontal.jpg,patient00002,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,\nThere is severe kyphosis centered at the mid...,\n1. MARKED KYPHOSIS WITH STATUS POST VERTEBRO...,"4: Possible Significant Abnormality/Change, m..."
2,train/patient00002/study1/view2_lateral.jpg,patient00002,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,\nThere is severe kyphosis centered at the mid...,\n1. MARKED KYPHOSIS WITH STATUS POST VERTEBRO...,"4: Possible Significant Abnormality/Change, m..."
3,train/patient00002/study2/view1_frontal.jpg,patient00002,"NARRATIVE:\nSINGLE VIEW OF THE CHEST, 4 VIEWS ...",NaN,\n1. SINGLE SUPINE PORTABLE FRONTAL VIEW OF TH...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
4,train/patient00003/study1/view1_frontal.jpg,patient00003,"NARRATIVE:\nCHEST, ONE VIEW: 2-10-2001\nFINDIN...","Costophrenic angles sharp, without evidence o...",\n1. NO EVIDENCE OF PNEUMOTHORAX.\n2. MILD INT...,2\nI have personally reviewed the images for ...
...,...,...,...,...,...,...
223457,valid/patient64736/study1/view1_frontal.jpg,patient64736,NARRATIVE:\nChest 1 View: 9/6/2003\n \nHISTORY...,NaN,\n \n1.THERE IS FREE INTRAPERITONEAL AIR SEEN...,"4-POSSIBLY SIGNIFICANT FINDING, MAY NEED ACTIO..."
223458,valid/patient64737/study1/view1_frontal.jpg,patient64737,NARRATIVE:\nPORTABLE CHEST RADIOGRAPH 1 VIEW: ...,NaN,\n1. INTERVAL REMOVAL OF RIGHT SUBCLAVIAN CENT...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
223459,valid/patient64738/study1/view1_frontal.jpg,patient64738,"NARRATIVE:\nChest 1 View, april 21\n \nHISTORY...",NaN,\n \n1.INTERVAL PLACEMENT OF A LEFT UPPER EX...,"2-ABNORMAL, PREVIOUSLY REPORTED\nI have perso..."
223460,valid/patient64739/study1/view1_frontal.jpg,patient64739,NARRATIVE:\nCOMPARISON: 7-21-2005\n \nIMPRESSI...,NaN,\n \nCARDIAC SILHOUETTE REMAINS MILDLY ENLARGE...,"2-ABNORMAL, PREVIOUSLY REPORTED\n \n"
223461,valid/patient64740/study1/view1_frontal.jpg,patient64740,NARRATIVE:\n SINGLE VIEW OF CHEST: 7/9/2017\n...,NaN,\n1. THERE HAS BEEN INTERVAL INCREASE ...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."

In [73]:
dataset.loc[:,"section_findings"] = dataset["section_findings"].fillna("")
dataset.loc[:,"section_impression"] = dataset["section_impression"].fillna("")
dataset.loc[:,"section_summary"] = dataset["section_summary"].fillna("")
dataset.loc[:,"sub_report"] = dataset["section_findings"] + dataset["section_impression"] + dataset["section_summary"]

indexes_to_remove = dataset.loc[dataset["sub_report"] == "", :].index.tolist()
dataset= dataset.loc[dataset["sub_report"] != "", :].reset_index(drop=True).drop(columns=['section_findings', 'section_impression', 'section_summary'])
dataset

,path_to_image,deid_patient_id,report,sub_report
0,train/patient00001/study1/view1_frontal.jpg,patient00001,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\n \nLeft subclavian central venous catheter w...
1,train/patient00002/study1/view1_frontal.jpg,patient00002,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,\nThere is severe kyphosis centered at the mid...
2,train/patient00002/study1/view2_lateral.jpg,patient00002,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,\nThere is severe kyphosis centered at the mid...
3,train/patient00002/study2/view1_frontal.jpg,patient00002,"NARRATIVE:\nSINGLE VIEW OF THE CHEST, 4 VIEWS ...",\n1. SINGLE SUPINE PORTABLE FRONTAL VIEW OF TH...
4,train/patient00003/study1/view1_frontal.jpg,patient00003,"NARRATIVE:\nCHEST, ONE VIEW: 2-10-2001\nFINDIN...","Costophrenic angles sharp, without evidence o..."
...,...,...,...,...
223453,valid/patient64736/study1/view1_frontal.jpg,patient64736,NARRATIVE:\nChest 1 View: 9/6/2003\n \nHISTORY...,\n \n1.THERE IS FREE INTRAPERITONEAL AIR SEEN...
223454,valid/patient64737/study1/view1_frontal.jpg,patient64737,NARRATIVE:\nPORTABLE CHEST RADIOGRAPH 1 VIEW: ...,\n1. INTERVAL REMOVAL OF RIGHT SUBCLAVIAN CENT...
223455,valid/patient64738/study1/view1_frontal.jpg,patient64738,"NARRATIVE:\nChest 1 View, april 21\n \nHISTORY...",\n \n1.INTERVAL PLACEMENT OF A LEFT UPPER EX...
223456,valid/patient64739/study1/view1_frontal.jpg,patient64739,NARRATIVE:\nCOMPARISON: 7-21-2005\n \nIMPRESSI...,\n \nCARDIAC SILHOUETTE REMAINS MILDLY ENLARGE...
223457,valid/patient64740/study1/view1_frontal.jpg,patient64740,NARRATIVE:\n SINGLE VIEW OF CHEST: 7/9/2017\n...,\n1. THERE HAS BEEN INTERVAL INCREASE ...

Get the patients IDs who have a unique image radio.

In [75]:
unique_patient = dataset["deid_patient_id"].value_counts(dropna=False).reset_index()
unique_patient = unique_patient.loc[unique_patient["count"] == 1, "deid_patient_id"].tolist()

Pick from this list a random sample of SAMPLE_SIZE patients. It'll be our positive matches.

In [76]:
SAMPLE_SIZE = 5000

In [77]:
rand_gen = random.Random(42)
pick_pos = rand_gen.sample(unique_patient, k=SAMPLE_SIZE)

In [78]:
filtered_df_pos = dataset[dataset['deid_patient_id'].isin(pick_pos)].reset_index(drop=True)

In [79]:
filtered_df_pos["target"] = 1
filtered_df_pos

,path_to_image,deid_patient_id,report,sub_report,target
0,train/patient00034/study1/view1_frontal.jpg,patient00034,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\n \nDiffuse reticular opacities which are non...,1
1,train/patient00068/study1/view1_frontal.jpg,patient00068,"NARRATIVE:\nPORTABLE CHEST, SINGLE AP VIEW: 12...",\nSingle AP portable view of the chest demonst...,1
2,train/patient00074/study1/view1_frontal.jpg,patient00074,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\n \nPatchy parenchymal density is identified ...,1
3,train/patient00076/study1/view1_frontal.jpg,patient00076,"NARRATIVE:\nPORTABLE CHEST, 5-4-2007\nCLINICAL...","\nAP portable chest, 5/4/2007 at 1536 hours is...",1
4,train/patient00129/study1/view1_frontal.jpg,patient00129,NARRATIVE:\nSINGLE PORTABLE UPRIGHT VIEW OF TH...,Single portable upright view of the chest de...,1
...,...,...,...,...,...
4995,valid/patient64722/study1/view1_frontal.jpg,patient64722,"NARRATIVE:\nPORTABLE CHEST, SINGLE VIEW: 11/14...",\n1. THERE IS FOCAL INCREASED OPACITY AT THE L...,1
4996,valid/patient64728/study1/view1_frontal.jpg,patient64728,NARRATIVE:\nChest 1 View 2-6-2011\n \nHISTORY:...,\n \n1. THE CARDIO MEDIASTINAL SILHOUETTE I...,1
4997,valid/patient64729/study1/view1_frontal.jpg,patient64729,"NARRATIVE:\nEXAM: Chest 1 View, Abdomen 1 View...",\n \n1.FEEDING TUBE AND SPINAL FIXATION RODS A...,1
4998,valid/patient64730/study1/view1_frontal.jpg,patient64730,NARRATIVE:\nEXAMINATION:\nPORTABLE CHEST 6/15...,Portable chest shows no change in the left su...,1
4999,valid/patient64731/study1/view1_frontal.jpg,patient64731,NARRATIVE:\nCHEST: 10/21/2021\nCOMPARISON: 10-...,\n1. AP VIEW OF THE CHEST DEMONSTRATES THE LEF...,1

Pick from the [unique_patient - positive matches], a random sample of SAMPLE_SIZE patients --> It'll be used for negative matches.

In [80]:
pick_neg = rand_gen.sample([item for item in unique_patient if item not in pick_pos], k=SAMPLE_SIZE)

In [81]:
filtered_df_neg = dataset_sub[dataset_sub['deid_patient_id'].isin(pick_neg)].reset_index(drop=True)

In [82]:
filtered_df_neg["target"] = 0
filtered_df_neg

,path_to_image,deid_patient_id,report,sub_report,target
0,train/patient00003/study1/view1_frontal.jpg,patient00003,"NARRATIVE:\nCHEST, ONE VIEW: 2-10-2001\nFINDIN...","Costophrenic angles sharp, without evidence o...",0
1,train/patient00029/study1/view1_frontal.jpg,patient00029,"NARRATIVE:\nEXAM: Chest 1 View, 3/2/2014\n \nC...",Left subclavian line tip in SVC. No associate...,0
2,train/patient00030/study1/view1_frontal.jpg,patient00030,"NARRATIVE:\nExam: Chest 1 View, 3/3/2000\n \nC...",\n \n1.SINGLE VIEW CHEST DEMONSTRATES STERNOTO...,0
3,train/patient00064/study1/view1_frontal.jpg,patient00064,NARRATIVE:\nSINGLE VIEW OF THE CHEST: 2/6/20...,\n Portable AP supine view of the chest demons...,0
4,train/patient00070/study1/view1_frontal.jpg,patient00070,NARRATIVE:\nEXAM: CHEST 1 VIEW 1/9/2009\n \nCL...,\n \n1.SINGLE FRONTAL VIEW OF THE CHEST DEMONS...,0
...,...,...,...,...,...
4995,valid/patient64727/study1/view1_frontal.jpg,patient64727,NARRATIVE:\nPORTABLE CHEST: 2006 JANUARY\nCOMP...,\n1. INTERVAL REMOVAL OF THE RIGHT PIGTAIL CAT...,0
4996,valid/patient64733/study1/view1_frontal.jpg,patient64733,"NARRATIVE:\nEXAM: Chest 1 View, 5/12/03\n \nCL...",\n \n1.BIBASILAR OPACITIES LIKELY REPRESENTING...,0
4997,valid/patient64734/study1/view1_frontal.jpg,patient64734,NARRATIVE:\nCHEST RADIOGRAPH: 2017/10/9 \n \...,\n \n 1. LOW LUNG VOLUMES. NO FOCAL OPACITI...,0
4998,valid/patient64737/study1/view1_frontal.jpg,patient64737,NARRATIVE:\nPORTABLE CHEST RADIOGRAPH 1 VIEW: ...,\n1. INTERVAL REMOVAL OF RIGHT SUBCLAVIAN CENT...,0
4999,valid/patient64740/study1/view1_frontal.jpg,patient64740,NARRATIVE:\n SINGLE VIEW OF CHEST: 7/9/2017\n...,\n1. THERE HAS BEEN INTERVAL INCREASE ...,0

Construct the negative matches by just swapping the reports based on the pathology detected. We keep the negative matches strategy building simple for this "Finding a baseline/reference" model.

In [83]:
impression = pd.read_json("./CheXpert/chexbert_labels/impression_fixed.json", lines=True)
impression = impression.sort_values(by="path_to_image", ignore_index=True)

In [84]:
impression = impression.drop("No Finding", axis=1)
impression = impression.drop(index=indexes_to_remove).reset_index(drop=True)

In [88]:
impression

,path_to_image,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,train/patient00001/study1/view1_frontal.jpg,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,1.0
1,train/patient00002/study1/view1_frontal.jpg,3.0,3.0,1.0,3.0,3.0,-1.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0
2,train/patient00002/study1/view2_lateral.jpg,3.0,3.0,1.0,3.0,3.0,-1.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0
3,train/patient00002/study2/view1_frontal.jpg,3.0,1.0,1.0,3.0,-1.0,-1.0,3.0,-1.0,3.0,-1.0,3.0,1.0,3.0
4,train/patient00003/study1/view1_frontal.jpg,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223453,valid/patient64736/study1/view1_frontal.jpg,3.0,0.0,3.0,3.0,1.0,0.0,3.0,3.0,3.0,0.0,3.0,3.0,1.0
223454,valid/patient64737/study1/view1_frontal.jpg,-1.0,3.0,1.0,3.0,3.0,-1.0,3.0,-1.0,0.0,3.0,3.0,3.0,1.0
223455,valid/patient64738/study1/view1_frontal.jpg,3.0,3.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0
223456,valid/patient64739/study1/view1_frontal.jpg,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0
223457,valid/patient64740/study1/view1_frontal.jpg,1.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,1.0,3.0

In [86]:
columns_keep = ['Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity', 'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis',
                'Pneumothorax', 'Pleural Effusion', 'Pleural Other', 'Fracture', 'Support Devices']

In [87]:
for col in columns_keep:
    impression[col] = impression[col].apply(lambda x: 3 if np.isnan(x) else x)

In [89]:
filtered_df_neg =  filtered_df_neg.merge(impression, on="path_to_image", how="inner")

In [90]:
filtered_df_neg

,path_to_image,deid_patient_id,report,sub_report,target,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,train/patient00003/study1/view1_frontal.jpg,patient00003,"NARRATIVE:\nCHEST, ONE VIEW: 2-10-2001\nFINDIN...","Costophrenic angles sharp, without evidence o...",0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,3.0
1,train/patient00029/study1/view1_frontal.jpg,patient00029,"NARRATIVE:\nEXAM: Chest 1 View, 3/2/2014\n \nC...",Left subclavian line tip in SVC. No associate...,0,3.0,3.0,1.0,3.0,3.0,3.0,3.0,-1.0,0.0,3.0,3.0,3.0,1.0
2,train/patient00030/study1/view1_frontal.jpg,patient00030,"NARRATIVE:\nExam: Chest 1 View, 3/3/2000\n \nC...",\n \n1.SINGLE VIEW CHEST DEMONSTRATES STERNOTO...,0,0.0,3.0,0.0,3.0,0.0,3.0,3.0,3.0,3.0,0.0,3.0,3.0,1.0
3,train/patient00064/study1/view1_frontal.jpg,patient00064,NARRATIVE:\nSINGLE VIEW OF THE CHEST: 2/6/20...,\n Portable AP supine view of the chest demons...,0,3.0,3.0,1.0,3.0,-1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0
4,train/patient00070/study1/view1_frontal.jpg,patient00070,NARRATIVE:\nEXAM: CHEST 1 VIEW 1/9/2009\n \nCL...,\n \n1.SINGLE FRONTAL VIEW OF THE CHEST DEMONS...,0,0.0,3.0,3.0,3.0,3.0,0.0,3.0,3.0,0.0,0.0,3.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,valid/patient64727/study1/view1_frontal.jpg,patient64727,NARRATIVE:\nPORTABLE CHEST: 2006 JANUARY\nCOMP...,\n1. INTERVAL REMOVAL OF THE RIGHT PIGTAIL CAT...,0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,0.0
4996,valid/patient64733/study1/view1_frontal.jpg,patient64733,"NARRATIVE:\nEXAM: Chest 1 View, 5/12/03\n \nCL...",\n \n1.BIBASILAR OPACITIES LIKELY REPRESENTING...,0,-1.0,3.0,1.0,3.0,3.0,-1.0,3.0,-1.0,3.0,3.0,3.0,3.0,3.0
4997,valid/patient64734/study1/view1_frontal.jpg,patient64734,NARRATIVE:\nCHEST RADIOGRAPH: 2017/10/9 \n \...,\n \n 1. LOW LUNG VOLUMES. NO FOCAL OPACITI...,0,3.0,3.0,0.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0
4998,valid/patient64737/study1/view1_frontal.jpg,patient64737,NARRATIVE:\nPORTABLE CHEST RADIOGRAPH 1 VIEW: ...,\n1. INTERVAL REMOVAL OF RIGHT SUBCLAVIAN CENT...,0,-1.0,3.0,1.0,3.0,3.0,-1.0,3.0,-1.0,0.0,3.0,3.0,3.0,1.0
4999,valid/patient64740/study1/view1_frontal.jpg,patient64740,NARRATIVE:\n SINGLE VIEW OF CHEST: 7/9/2017\n...,\n1. THERE HAS BEEN INTERVAL INCREASE ...,0,1.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,1.0,3.0

In [91]:
for i in filtered_df_neg.index:
    temp_df = impression.merge(filtered_df_neg.iloc[[i]], on=columns_keep, how="left", indicator=True)
    temp_path = rand_gen.sample(temp_df.loc[temp_df["_merge"] == "left_only", "path_to_image_x"].tolist(), k=1)
    filtered_df_neg.loc[i,"report"] = dataset.loc[dataset["path_to_image"] == temp_path[0], "report"].item()
    filtered_df_neg.loc[i,"sub_report"] = dataset.loc[dataset["path_to_image"] == temp_path[0], "sub_report"].item()

In [92]:
filtered_df_neg = filtered_df_neg.drop(columns_keep, axis=1)

In [93]:
filtered_df_neg

,path_to_image,deid_patient_id,report,sub_report,target
0,train/patient00003/study1/view1_frontal.jpg,patient00003,NARRATIVE:\nUPRIGHT VIEW OF THE CHEST: 8-30-20...,\n \n 1. REDEMONSTRATION OF PIGTAIL DRAIN WIT...,0
1,train/patient00029/study1/view1_frontal.jpg,patient00029,NARRATIVE:\nCHEST X-RAY: 4-20-04\n \n COMPARIS...,\n \n 1. SINGLE SUPINE AP VIEW OF THE CHEST ...,0
2,train/patient00030/study1/view1_frontal.jpg,patient00030,NARRATIVE:\nChest 2 Views JANUARY 03RD\n \nC...,"\n \n1. BIBASILAR OPACITIES, ATELECTASIS VERS...",0
3,train/patient00064/study1/view1_frontal.jpg,patient00064,"NARRATIVE:\nCHEST, ONE VIEW: 12/12/2021.\n \n...",\n \n 1. THIS STUDY IS LIMITED BY SIGNIFICAN...,0
4,train/patient00070/study1/view1_frontal.jpg,patient00070,"NARRATIVE:\nChest 1 View, 9/9/2018\n \nHISTORY...",\n \n1.AP SEMIUPRIGHT CHEST RADIOGRAPH DEMON...,0
...,...,...,...,...,...
4995,valid/patient64727/study1/view1_frontal.jpg,patient64727,"NARRATIVE:\nChest 2 Views, 3-2-2015\n \nHISTOR...",\n \n1.TWO VIEWS OF THE CHEST DEMONSTRATE A ...,0
4996,valid/patient64733/study1/view1_frontal.jpg,patient64733,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\nAccession 726-631-029-5:\nThere has been int...,0
4997,valid/patient64734/study1/view1_frontal.jpg,patient64734,NARRATIVE:\nEXAM: Chest 2 Views\n \nDATE: 12/2...,\n \n1. THERE ARE LOW LUNG VOLUMES. THERE IS...,0
4998,valid/patient64737/study1/view1_frontal.jpg,patient64737,NARRATIVE:\nONE-VIEW CHEST X-RAY: \n \n COMPA...,\n \n 1. LIMITED EVALUATION SECONDARY TO BLU...,0
4999,valid/patient64740/study1/view1_frontal.jpg,patient64740,"NARRATIVE:\nExam: Chest 1 View, May 2\n \nClin...",\n \n1.AP SEMIERECT CHEST RADIOGRAPH DEMONSTRA...,0

In [94]:
sample_dataset = pd.concat([filtered_df_pos,filtered_df_neg], ignore_index=True)
sample_dataset = sample_dataset.sample(frac=1, random_state=42).reset_index(drop=True)
sample_dataset["report_length"] = sample_dataset["report"].apply(lambda x: len(x.split(" ")))
sample_dataset["sub_report_length"] = sample_dataset["sub_report"].apply(lambda x: len(x.split(" ")))

In [95]:
sample_dataset

,path_to_image,deid_patient_id,report,sub_report,target,report_length,sub_report_length
0,train/patient25675/study1/view1_frontal.jpg,patient25675,NARRATIVE:\nCHEST ONE VIEW: 12/18/2009.\n \n ...,A single upright radiograph of the chest on ...,0,151,103
1,train/patient63300/study1/view1_frontal.jpg,patient63300,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\n \nChest radiograph on 7-2-2011: Interval pl...,1,229,178
2,train/patient34015/study1/view1_frontal.jpg,patient34015,NARRATIVE:\nSINGLE VIEW OF THE CHEST: APRIL ...,Single frontal view of the chest demonstrat...,1,170,116
3,train/patient63548/study1/view1_frontal.jpg,patient63548,NARRATIVE:\nSINGLE VIEW OF THE CHEST: 2/28/20...,\n \n 1. SINGLE PORTABLE SEMIUPRIGHT AP VIEW...,1,124,83
4,train/patient62581/study1/view1_frontal.jpg,patient62581,"NARRATIVE:\nExam: Chest 1 View, 9/26/2017\n \n...",\n \n1.SINGLE SEMIUPRIGHT PORTABLE VIEW OF THE...,1,114,77
...,...,...,...,...,...,...,...
9995,train/patient14781/study1/view1_frontal.jpg,patient14781,NARRATIVE:\nChest 2 Views 3/18/02\n \nCLINICAL...,\n \n1.FRONTAL AND LATERAL VIEWS OF THE CHEST ...,0,102,64
9996,train/patient03890/study1/view1_frontal.jpg,patient03890,NARRATIVE:\nCHEST AP PORTABLE: 3-17\nCOMPARISO...,\nSerial radiographs of the chest on 3/17/2017...,0,175,149
9997,train/patient07465/study1/view1_frontal.jpg,patient07465,NARRATIVE:\nSINGLE VIEW PORTABLE CHEST X-RAY O...,\n1. INTERVAL PLACEMENT OF CATHETER IN PREVIOU...,0,182,145
9998,train/patient16949/study1/view1_frontal.jpg,patient16949,NARRATIVE:\nSINGLE PORTABLE VIEW OF THE CHEST:...,An AP portable upright view of the chest was ...,1,124,94
9999,train/patient44063/study1/view1_frontal.jpg,patient44063,NARRATIVE:\nSINGLE VIEW PORTABLE CHEST: April ...,\n1. INTERVAL PLACEMENT OF A FEEDING TUBE WHIC...,0,76,36

In [96]:
sample_dataset.to_csv("./chexpert_sample_dataset.csv")