<p align="center">
  <img src="https://seekvectorlogo.com/wp-content/uploads/2018/01/kayak-vector-logo.png" width="200">
</p>

# Plan your trip with Kayak
**Auteur :** Aicha FATHELLAH - Formation Fullstack Data Engineering
**Objectif :** Recommander les 5 meilleures destinations francaises et les 20 meilleurs hotels associes, en combinant donnees meteo (API OpenWeatherMap) et donnees hotelieres (scraping Booking.com), stockees sur AWS S3 / RDS.

---

**Pipeline :**
`Geocodage` -> `API Meteo` -> `Scraping Hotels` -> `Nettoyage & Scoring` -> `S3 (Data Lake)` -> `RDS (Data Warehouse)` -> `Visualisation`

In [ ]:
# Mise à jour de pip puis installation des dépendances
# Mise à jour de pip puis installation des dépendances
%pip install --upgrade pip
%pip install -r requirements.txt

## 1. Installation & Imports

In [7]:
%pip install selenium webdriver-manager boto3 sqlalchemy psycopg2-binary plotly geopy python-dotenv -q

# Bibliotheques standard Python
import json, time, re, os
from io import StringIO
from pathlib import Path

# Manipulation de donnees
import pandas as pd      # DataFrames : lecture, transformation, export CSV
import numpy as np       # Calculs numeriques

# Requetes HTTP
import requests          # Appels API REST (OpenWeatherMap)

# Visualisation interactive
import plotly.express as px  # Cartes Mapbox interactives

# Geocodage
from geopy.geocoders import Nominatim  # Conversion nom -> coordonnees GPS

# Scraping web
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

# Cloud AWS
import boto3
from sqlalchemy import create_engine

# Securite des cles API
from dotenv import load_dotenv
load_dotenv()

# Dossier de sortie des donnees (cree s'il n'existe pas)
DATA = Path("data")
DATA.mkdir(exist_ok=True)

print("Environnement pret")

Note: you may need to restart the kernel to use updated packages.
Environnement pret

## 2. Geocodage des 35 destinations (Nominatim)
Recuperation des coordonnees GPS via l'API OpenStreetMap : pause d'1 s entre chaque ville pour respecter le rate limit.

La liste reprend exactement les 35 villes imposees par le cahier des charges (source One Week In).

In [8]:
# Liste officielle des 35 destinations imposees par le cahier des charges
villes = [
    "Mont Saint Michel", "St Malo", "Bayeux", "Le Havre", "Rouen", "Paris",
    "Amiens", "Lille", "Strasbourg", "Chateau du Haut Koenigsbourg", "Colmar",
    "Eguisheim", "Besancon", "Dijon", "Annecy", "Grenoble", "Lyon",
    "Gorges du Verdon", "Bormes les Mimosas", "Cassis", "Marseille",
    "Aix en Provence", "Avignon", "Uzes", "Nimes", "Aigues Mortes",
    "Saintes Maries de la Mer", "Collioure", "Carcassonne", "Ariege",
    "Toulouse", "Montauban", "Biarritz", "Bayonne", "La Rochelle"
]

# Initialisation du geocodeur Nominatim (OpenStreetMap, gratuit, sans cle API)
# user_agent obligatoire pour identifier notre application aupres du serveur
geolocator = Nominatim(user_agent="kayak_project_agent")
villes_data = []

for ville in villes:
    try:
        # On precise "France" pour eviter les homonymes
        loc = geolocator.geocode(f"{ville}, France")
        if loc:
            villes_data.append({
                "city": ville,
                "latitude": loc.latitude,
                "longitude": loc.longitude
            })
            print(f"{ville}")
        else:
            print(f"{ville} - non trouve")

        # Pause obligatoire : Nominatim limite a 1 requete/seconde
        time.sleep(1)
    except Exception as e:
        print(f"Erreur {ville}: {e}")

# Creation du DataFrame et ajout d'un identifiant unique par ville
df_villes = pd.DataFrame(villes_data)
df_villes.insert(0, "city_id", range(1, len(df_villes) + 1))

# Sauvegarde locale pour ne pas avoir a relancer le geocodage
df_villes.to_csv(DATA / "villes_coords.csv", index=False)

print(f"\nGeocodage termine : {len(df_villes)}/35 villes")
display(df_villes.head())

Mont Saint Michel
St Malo
Bayeux
Le Havre
Rouen
Paris
Amiens
Lille
Strasbourg
Chateau du Haut Koenigsbourg
Colmar
Eguisheim
Besancon
Dijon
Annecy
Grenoble
Lyon
Gorges du Verdon
Bormes les Mimosas
Cassis
Marseille
Aix en Provence
Avignon
Uzes
Nimes
Aigues Mortes
Saintes Maries de la Mer
Collioure
Carcassonne
Ariege
Toulouse
Montauban
Biarritz
Bayonne
La Rochelle

Geocodage termine : 35/35 villes

   city_id               city   latitude  longitude
0        1  Mont Saint Michel  48.635954  -1.511460
1        2            St Malo  48.649518  -2.026041
2        3             Bayeux  49.276462  -0.702474
3        4           Le Havre  49.493898   0.107973
4        5              Rouen  49.440459   1.093966

## 3. Donnees meteo : API OpenWeatherMap
Cle API chargee depuis `config/openweather.env` (variable `OPENWEATHER_API_KEY`).

Endpoint : `data/2.5/forecast` (previsions 5 jours / 3 h, gratuit). L'API One Call sur 7 jours necessite desormais un abonnement avec moyen de paiement enregistre : pour rester dans une logique de cout maitrise, on utilise l'endpoint gratuit et on **agrege l'ensemble de l'horizon de prevision** (et non un seul creneau), afin de refleter la meteo a venir et non un instantane.

In [9]:
# Chargement de la cle API depuis le fichier .env (jamais en dur dans le code)
load_dotenv(dotenv_path=Path("config/openweather.env"))
API_KEY = os.getenv("OPENWEATHER_API_KEY")

weather_results = []

for _, row in df_villes.iterrows():
    # units=metric -> temperatures en Celsius ; lang=fr -> descriptions en francais
    url = (
        f"https://api.openweathermap.org/data/2.5/forecast"
        f"?lat={row['latitude']}&lon={row['longitude']}"
        f"&appid={API_KEY}&units=metric&lang=fr"
    )
    resp = requests.get(url)
    if resp.status_code == 200:
        previsions = resp.json()["list"]   # 40 creneaux : 5 jours / 3 h

        # Agregation sur tout l'horizon disponible (correction : avant, un seul creneau)
        temps = [p["main"]["temp"] for p in previsions]
        pops  = [p.get("pop", 0) for p in previsions]              # probabilite de pluie [0-1]
        pluie = [p.get("rain", {}).get("3h", 0) for p in previsions]  # volume de pluie (mm)

        weather_results.append({
            "city_id": row["city_id"],
            "city": row["city"],
            "temp": round(float(np.mean(temps)), 1),       # temperature moyenne sur l'horizon
            "rain_prob": round(float(np.mean(pops)), 2),   # probabilite moyenne de pluie
            "rain_volume": round(float(np.sum(pluie)), 1), # volume de pluie cumule (mm)
            "weather_description": previsions[0]["weather"][0]["description"]
        })
        print(f"{row['city']}")
    else:
        print(f"{row['city']} - code {resp.status_code}")

    time.sleep(0.2)  # rester dans les limites du plan gratuit (60 req/min)

# Fusion des donnees meteo avec les coordonnees GPS
weather_df = pd.DataFrame(weather_results)
if weather_df.empty:
    if not API_KEY:
        raise ValueError(
            "OPENWEATHER_API_KEY introuvable. Vérifiez que 'config/openweather.env' existe "
            "et contient la variable OPENWEATHER_API_KEY, ou exportez-la dans l'environnement."
        )
    else:
        raise ValueError(
            "Aucune donnée météo n'a été récupérée. Vérifiez que la clé OPENWEATHER_API_KEY est valide "
            "et que les requêtes vers OpenWeatherMap renvoient 200 (resp.status_code)."
        )

expected_cols = ["city_id", "temp", "rain_prob", "rain_volume", "weather_description"]
missing = [c for c in expected_cols if c not in weather_df.columns]
if missing:
    raise ValueError(f"Colonnes manquantes dans weather_results : {missing}")

df_weather_final = pd.merge(
    df_villes,
    weather_df[expected_cols],
    on="city_id",
    how="left"
)
df_weather_final.to_csv(DATA / "villes_meteo_coords.csv", index=False)

print(f"\nMeteo agregee pour {len(df_weather_final)} villes")
display(df_weather_final.head())

Mont Saint Michel
St Malo
Bayeux
Le Havre
Rouen
Paris
Amiens
Lille
Strasbourg
Chateau du Haut Koenigsbourg
Colmar
Eguisheim
Besancon
Dijon
Annecy
Grenoble
Lyon
Gorges du Verdon
Bormes les Mimosas
Cassis
Marseille
Aix en Provence
Avignon
Uzes
Nimes
Aigues Mortes
Saintes Maries de la Mer
Collioure
Carcassonne
Ariege
Toulouse
Montauban
Biarritz
Bayonne
La Rochelle

Meteo agregee pour 35 villes

,city_id,city,latitude,longitude,temp,rain_prob,rain_volume,weather_description
0,1,Mont Saint Michel,48.635954,-1.511460,22.9,0.14,8.2,peu nuageux
1,2,St Malo,48.649518,-2.026041,20.8,0.09,6.2,peu nuageux
2,3,Bayeux,49.276462,-0.702474,23.6,0.16,9.3,nuageux
3,4,Le Havre,49.493898,0.107973,21.8,0.16,9.7,peu nuageux
4,5,Rouen,49.440459,1.093966,28.0,0.04,1.3,nuageux

## 4. Scraping Booking.com : Selenium (Chrome headless)
`requests` est bloque par Booking (code 202 + JS dynamique) -> utilisation de Selenium.
Strategie : scroll progressif pour declencher le lazy-loading, limite a 20 hotels par ville, checkpoint CSV apres chaque ville.

In [10]:
def scrape_hotels_selenium(city):
    """
    Scrape les hotels d'une ville sur Booking.com via Selenium Chrome headless.

    Pourquoi Selenium et pas requests ?
    -> Booking.com charge son contenu via JavaScript (rendu dynamique).
    -> requests ne recupere que le HTML statique : les cartes hotels sont absentes.
       Selenium pilote un vrai navigateur qui execute le JS.

    Retourne : list[dict] {city, hotel_name, url, rating, description}
    """
    opts = Options()
    opts.add_argument("--headless")
    opts.add_argument("--window-size=1920,1080")
    opts.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                      "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36")

    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=opts)
    hotels = []
    url = f"https://www.booking.com/searchresults.fr.html?ss={city.replace(' ', '%20')}"

    try:
        driver.get(url)
        time.sleep(5)  # chargement initial

        # Scroll progressif pour declencher le lazy-loading des cartes hotels
        for i in range(4):
            driver.execute_script(f"window.scrollTo(0, {(i+1)*1000});")
            time.sleep(2)

        for card in driver.find_elements(By.CSS_SELECTOR, '[data-testid="property-card"]')[:20]:
            try:
                name      = card.find_element(By.CSS_SELECTOR, '[data-testid="title"]').text.strip()
                hotel_url = card.find_element(By.CSS_SELECTOR, '[data-testid="title-link"]').get_attribute("href")

                # Note de l'hotel (ex : "Superb 9.4" -> 9.4)
                try:
                    raw    = card.find_element(By.CSS_SELECTOR, '[data-testid="review-score"]').text
                    m      = re.search(r"(\d[,\.]\d)", raw)
                    rating = float(m.group(1).replace(",", ".")) if m else 0.0
                except:
                    rating = 0.0

                # Description / type de chambre (charge tardivement par JS, souvent N/A)
                try:
                    desc = card.find_element(By.CSS_SELECTOR, '[data-testid="recommended-units"]').text.strip()
                except:
                    desc = "N/A"

                if name:
                    hotels.append({
                        "city": city,
                        "hotel_name": name,
                        "url": hotel_url,
                        "rating": rating,
                        "description": desc
                    })
            except:
                continue
    finally:
        driver.quit()

    return hotels

In [11]:
OUTPUT_FILE = DATA / "hotels_booking_35_villes.csv"
final_data  = []

for _, row in df_villes.iterrows():
    print(f"[{row['city_id']}/35] {row['city']}...")
    try:
        results = scrape_hotels_selenium(row["city"])

        # Ajout du city_id a chaque hotel pour la cle de jointure
        for h in results:
            h["city_id"] = row["city_id"]

        final_data.extend(results)

        # Checkpoint : sauvegarde apres chaque ville
        pd.DataFrame(final_data).to_csv(OUTPUT_FILE, index=False)
        print(f"  -> {len(results)} hotels | total cumule : {len(final_data)}")
    except Exception as e:
        print(f"Erreur : {e}")

    time.sleep(5)

df_hotels_raw = pd.DataFrame(final_data)
print(f"\nScraping termine - {len(df_hotels_raw)} lignes")
display(df_hotels_raw.head())

[1/35] Mont Saint Michel...
  -> 3 hotels | total cumule : 3
[2/35] St Malo...
  -> 3 hotels | total cumule : 6
[3/35] Bayeux...
  -> 3 hotels | total cumule : 9
[4/35] Le Havre...
  -> 3 hotels | total cumule : 12
[5/35] Rouen...
  -> 3 hotels | total cumule : 15
[6/35] Paris...
  -> 3 hotels | total cumule : 18
[7/35] Amiens...
  -> 3 hotels | total cumule : 21
[8/35] Lille...
  -> 3 hotels | total cumule : 24
[9/35] Strasbourg...
  -> 3 hotels | total cumule : 27
[10/35] Chateau du Haut Koenigsbourg...
  -> 3 hotels | total cumule : 30
[11/35] Colmar...
  -> 3 hotels | total cumule : 33
[12/35] Eguisheim...
  -> 3 hotels | total cumule : 36
[13/35] Besancon...
  -> 3 hotels | total cumule : 39
[14/35] Dijon...
  -> 3 hotels | total cumule : 42
[15/35] Annecy...
  -> 3 hotels | total cumule : 45
[16/35] Grenoble...
  -> 3 hotels | total cumule : 48
[17/35] Lyon...
  -> 3 hotels | total cumule : 51
[18/35] Gorges du Verdon...
  -> 3 hotels | total cumule : 54
[19/35] Bormes les Mimosas...
  -> 3 hotels | total cumule : 57
[20/35] Cassis...
  -> 3 hotels | total cumule : 60
[21/35] Marseille...
  -> 3 hotels | total cumule : 63
[22/35] Aix en Provence...
  -> 3 hotels | total cumule : 66
[23/35] Avignon...
  -> 3 hotels | total cumule : 69
[24/35] Uzes...
  -> 3 hotels | total cumule : 72
[25/35] Nimes...
  -> 3 hotels | total cumule : 75
[26/35] Aigues Mortes...
  -> 3 hotels | total cumule : 78
[27/35] Saintes Maries de la Mer...
  -> 3 hotels | total cumule : 81
[28/35] Collioure...
  -> 3 hotels | total cumule : 84
[29/35] Carcassonne...
  -> 3 hotels | total cumule : 87
[30/35] Ariege...
  -> 3 hotels | total cumule : 90
[31/35] Toulouse...
  -> 3 hotels | total cumule : 93
[32/35] Montauban...
  -> 3 hotels | total cumule : 96
[33/35] Biarritz...
  -> 3 hotels | total cumule : 99
[34/35] Bayonne...
  -> 3 hotels | total cumule : 102
[35/35] La Rochelle...
  -> 3 hotels | total cumule : 105

Scraping termine - 105 lignes

,city,hotel_name,url,rating,description,city_id
0,Mont Saint Michel,Auberge Saint Pierre,https://www.booking.com/hotel/fr/auberge-saint...,8.0,N/A,1
1,Mont Saint Michel,Appart Standing - La Coque d'Or - Mont-St-Michel,https://www.booking.com/hotel/fr/la-coque-d-or...,9.6,N/A,1
2,Mont Saint Michel,"Chez Adèle, au pied de l'Abbaye",https://www.booking.com/hotel/fr/chez-adele-le...,9.1,N/A,1
3,St Malo,L'Emeraude,https://www.booking.com/hotel/fr/l-39-emeraude...,9.4,N/A,2
4,St Malo,Grand Hotel de Courtoisville,https://www.booking.com/hotel/fr/grand-de-cour...,9.4,N/A,2

## 5. Nettoyage, geocodage des hotels, agregation et score de voyage
**Nettoyage :** suppression des lignes sans note, deduplication par `(hotel_name, city)`.
**Geocodage des hotels :** le cahier des charges demande la latitude / longitude de chaque hotel. On interroge Nominatim sur "nom hotel, ville, France" ; en cas d'echec, on retombe sur les coordonnees du centre-ville (fallback).
**Score de voyage :** chaque critere (temperature, note hoteliere, faible pluie) est normalise entre 0 et 1, puis pondere. Cette methode est plus rigoureuse que de melanger des echelles differentes.

In [13]:
# --- Nettoyage ---
df_clean = pd.read_csv(DATA / "hotels_booking_35_villes.csv").copy()
df_clean = (df_clean
    .dropna(subset=["rating"])                          # uniquement les hotels notes
    .drop_duplicates(subset=["hotel_name", "city"])     # suppression des doublons
)
df_clean["description"] = df_clean["description"].fillna("N/A")

# --- Geocodage de chaque hotel (coordonnees propres a l'etablissement) ---
# Recuperation des coordonnees de centre-ville pour le fallback
df_city_coords = df_weather_final[["city", "latitude", "longitude"]].rename(
    columns={"latitude": "city_lat", "longitude": "city_lon"})
df_clean = df_clean.merge(df_city_coords, on="city", how="left")

geo_hotels = Nominatim(user_agent="kayak_hotels_agent")
hotel_lat, hotel_lon = [], []

for _, h in df_clean.iterrows():
    try:
        loc = geo_hotels.geocode(f"{h['hotel_name']}, {h['city']}, France")
        if loc:
            hotel_lat.append(loc.latitude)
            hotel_lon.append(loc.longitude)
        else:
            # Fallback : coordonnees du centre-ville
            hotel_lat.append(h["city_lat"])
            hotel_lon.append(h["city_lon"])
    except Exception:
        hotel_lat.append(h["city_lat"])
        hotel_lon.append(h["city_lon"])
    time.sleep(1)  # Nominatim : 1 requete/seconde

df_clean["latitude"]  = hotel_lat
df_clean["longitude"] = hotel_lon
df_clean = df_clean.drop(columns=["city_lat", "city_lon"])
df_clean.to_csv(DATA / "hotels_cleaned_full.csv", index=False)

# --- Score agrege par ville ---
df_city_scores = (df_clean
    .groupby(["city_id", "city"])["rating"]
    .mean().round(2)
    .reset_index()
    .rename(columns={"rating": "mean_hotel_rating"})
)
df_city_scores.to_csv(DATA / "villes_scores_aggregated.csv", index=False)

# --- Fusion meteo + hotels ---
# LEFT JOIN : on garde toutes les villes meme sans hotel scrape
df_final = pd.merge(df_weather_final, df_city_scores, on=["city_id", "city"], how="left")

# --- Calcul du travel_score (normalisation min-max puis ponderation) ---
def minmax(s):
    etendue = s.max() - s.min()
    return (s - s.min()) / etendue if etendue else s * 0

df_final["temp_norm"]   = minmax(df_final["temp"])              # plus chaud = mieux
df_final["rating_norm"] = minmax(df_final["mean_hotel_rating"]) # mieux note = mieux
df_final["rain_norm"]   = 1 - minmax(df_final["rain_prob"])     # moins de pluie = mieux

# Ponderation : 40% temperature, 40% qualite hoteliere, 20% faible pluie
df_final["travel_score"] = (
    0.4 * df_final["temp_norm"]
    + 0.4 * df_final["rating_norm"]
    + 0.2 * df_final["rain_norm"]
) * 100  # echelle 0-100 lisible

df_final = df_final.sort_values("travel_score", ascending=False)
df_final.to_csv(DATA / "kayak_final_enriched_data.csv", index=False)

print(f"Dataset final : {df_final.shape}")
display(df_final.head(10))

Dataset final : (35, 13)

,city_id,city,latitude,longitude,temp,rain_prob,rain_volume,weather_description,mean_hotel_rating,temp_norm,rating_norm,rain_norm,travel_score
23,24,Uzes,44.012128,4.419672,28.7,0.01,0.1,ciel dégagé,9.50,0.718182,1.000000,0.95,87.727273
21,22,Aix en Provence,43.529842,5.447474,29.5,0.04,1.4,nuageux,8.83,0.790909,0.839329,0.80,81.209505
24,25,Nimes,43.837425,4.360069,29.0,0.00,0.0,peu nuageux,8.57,0.745455,0.776978,1.00,80.897319
13,14,Dijon,47.321581,5.041470,30.0,0.01,0.2,peu nuageux,8.23,0.836364,0.695444,0.95,80.272291
31,32,Montauban,44.017584,1.354999,29.9,0.02,0.5,peu nuageux,8.17,0.827273,0.681055,0.90,78.333115
8,9,Strasbourg,48.584614,7.750713,29.9,0.01,0.2,nuageux,8.03,0.827273,0.647482,0.95,77.990190
16,17,Lyon,45.757814,4.832011,30.1,0.01,0.3,ciel dégagé,7.87,0.845455,0.609113,0.95,77.182690
27,28,Collioure,42.525050,3.083155,27.4,0.00,0.0,ciel dégagé,8.77,0.600000,0.824940,1.00,76.997602
28,29,Carcassonne,43.213036,2.349107,28.3,0.00,0.0,ciel dégagé,8.37,0.681818,0.729017,1.00,76.433399
30,31,Toulouse,43.604464,1.444243,29.0,0.02,0.6,peu nuageux,8.30,0.745455,0.712230,0.90,76.307390

## 6. Data Lake : AWS S3
Cles AWS chargees depuis `config/aws.env`.
Les 4 fichiers CSV transformes sont envoyes dans le bucket S3 (couches silver / gold du Data Lake).

In [ ]:
# Chargement des cles AWS depuis le fichier .env (jamais en dur dans le code)
load_dotenv(dotenv_path=Path("config/aws.env"), override=True)

ACCESS_KEY  = os.getenv("AWS_ACCESS_KEY_ID")
SECRET_KEY  = os.getenv("AWS_SECRET_ACCESS_KEY")
BUCKET_NAME = os.getenv("S3_BUCKET_NAME")
REGION      = os.getenv("AWS_REGION", "eu-west-3")

# Session AWS authentifiee
session   = boto3.Session(aws_access_key_id=ACCESS_KEY,
                          aws_secret_access_key=SECRET_KEY,
                          region_name=REGION)
s3        = session.resource("s3")
s3_client = session.client("s3")

# Creation du bucket S3 s'il n'existe pas encore (role de Data Lake : stockage brut scalable)
try:
    s3_client.head_bucket(Bucket=BUCKET_NAME)
    print(f"Bucket '{BUCKET_NAME}' deja existant.")
except:
    s3.create_bucket(Bucket=BUCKET_NAME,
                     CreateBucketConfiguration={"LocationConstraint": REGION})
    print(f"Bucket '{BUCKET_NAME}' cree.")

# Upload des 4 fichiers CSV transformes vers S3
for fname in [
    "villes_meteo_coords.csv",
    "hotels_cleaned_full.csv",
    "villes_scores_aggregated.csv",
    "kayak_final_enriched_data.csv"
]:
    local_path = DATA / fname
    if local_path.exists():
        s3.Bucket(BUCKET_NAME).upload_file(str(local_path), fname)  # cle S3 = nom du fichier
        print(f"{fname} envoye")
    else:
        print(f"{fname} non trouve localement")

## 7. Data Warehouse : AWS RDS (PostgreSQL)
Cles chargees depuis `config/aws.env`.
Deux tables relationnelles : `cities` (1 ligne / ville) et `hotels` (N lignes / ville, liees par `city_id`).

In [ ]:
# Chargement des identifiants RDS depuis le fichier .env
load_dotenv(dotenv_path=Path("config/aws.env"), override=True)

DB_USER     = os.getenv("RDS_USERNAME")
DB_PASSWORD = os.getenv("RDS_PASSWORD")
DB_HOST     = os.getenv("RDS_HOSTNAME")              # Endpoint de l'instance RDS
DB_PORT     = os.getenv("RDS_PORT", "5432")          # Port par defaut de PostgreSQL
DB_NAME     = os.getenv("RDS_DB_NAME", "postgres")   # Nom de la base de donnees

# Connexion via SQLAlchemy : postgresql://user:password@host:port/database
engine = create_engine(f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

try:
    # Table cities : 1 ligne par ville (coordonnees, meteo, score)
    df_final.to_sql("cities", con=engine, if_exists="replace", index=False)
    print(f"Table 'cities' injectee ({len(df_final)} destinations)")

    # Table hotels : N lignes par ville, liees par city_id (relation one-to-many)
    df_clean.to_sql("hotels", con=engine, if_exists="replace", index=False)
    print(f"Table 'hotels' injectee ({len(df_clean)} etablissements)")

except Exception as e:
    print(f"Erreur RDS : {e}")
    print("-> Verifier le Security Group AWS (port 5432, IP autorisee)")

## 8. Visualisation : Cartes interactives Plotly
### Carte 1 : Top 5 destinations (score meteo + hotels)

In [14]:
# --- Tableau Top 5 destinations ---
top_5_display = df_final.head(5)[["city", "temp", "rain_prob", "mean_hotel_rating", "travel_score"]].copy()
top_5_display.columns = ["Destination", "Temperature (C)", "Prob. pluie", "Note hotels", "Score voyage"]
top_5_display = top_5_display.round(2).reset_index(drop=True)
top_5_display.index += 1
display(top_5_display)

# --- Carte interactive : Top 5 destinations ---
top_5 = df_final.head(5)
fig = px.scatter_mapbox(
    top_5,
    lat="latitude", lon="longitude",
    hover_name="city",
    hover_data={
        "latitude": False, "longitude": False,
        "temp": ":.1f",
        "rain_prob": ":.2f",
        "mean_hotel_rating": ":.1f"
    },
    color="temp",
    size="travel_score",
    color_continuous_scale=px.colors.sequential.YlOrRd,
    size_max=18, zoom=5,
    mapbox_style="open-street-map",
    title="Top 5 Destinations - Meilleur compromis Météo / Hôtels"
)
fig.update_layout(margin={"r": 10, "t": 50, "l": 10, "b": 10})
fig.show()

       Destination  Temperature (C)  Prob. pluie  Note hotels  Score voyage
1             Uzes             28.7         0.01         9.50         87.73
2  Aix en Provence             29.5         0.04         8.83         81.21
3            Nimes             29.0         0.00         8.57         80.90
4            Dijon             30.0         0.01         8.23         80.27
5        Montauban             29.9         0.02         8.17         78.33

### Carte 2 : Top 20 hotels les mieux notes

In [15]:
# --- Tableau Top 20 hotels ---
top_20 = df_clean.sort_values("rating", ascending=False).head(20)

top_20_display = top_20[["hotel_name", "city", "rating", "url"]].copy()
top_20_display.columns = ["Hotel", "Ville", "Note", "URL"]
top_20_display = top_20_display.reset_index(drop=True)
top_20_display.index += 1
display(top_20_display)

# --- Carte interactive : Top 20 hotels (coordonnees propres a chaque hotel) ---
fig2 = px.scatter_mapbox(
    top_20,
    lat="latitude", lon="longitude",
    hover_name="hotel_name",
    hover_data={
        "latitude": False, "longitude": False,
        "city": True,
        "rating": ":.1f"
    },
    color="rating",
    size="rating",
    color_continuous_scale=px.colors.sequential.Viridis,
    zoom=5, mapbox_style="open-street-map",
    title="<b>Top 20 Hôtels les mieux notés en France</b>"
)
fig2.update_layout(margin={"r": 10, "t": 50, "l": 10, "b": 10})
fig2.show()

,Hotel,Ville,Note,URL
1,La Maison du Puisatier • Centre historique • P...,Uzes,9.8,https://www.booking.com/hotel/fr/la-maison-du-...
2,GITE LE COQ ROUGE,Eguisheim,9.7,https://www.booking.com/hotel/fr/gite-le-coq-r...
3,Tiny house au cœur de Bayeux,Bayeux,9.7,https://www.booking.com/hotel/fr/tiny-house-au...
4,Appart Standing - La Coque d'Or - Mont-St-Michel,Mont Saint Michel,9.6,https://www.booking.com/hotel/fr/la-coque-d-or...
5,Gite Le Petit Malsbach Eguisheim 3 étoiles,Eguisheim,9.5,https://www.booking.com/hotel/fr/gite-le-petit...
6,Vanille Bourbon,Montauban,9.5,https://www.booking.com/hotel/fr/vanille-bourb...
7,Le rohan sawadee,Colmar,9.5,https://www.booking.com/hotel/fr/le-rohan-sawa...
8,Les Gîtes du Racème,Chateau du Haut Koenigsbourg,9.4,https://www.booking.com/hotel/fr/mannala-blien...
9,Maison Longuevie,Amiens,9.4,https://www.booking.com/hotel/fr/longuevie.fr....
10,Une chambre à Uzès,Uzes,9.4,https://www.booking.com/hotel/fr/une-chambre-a...
11,Chalet Les Prés,Chateau du Haut Koenigsbourg,9.4,https://www.booking.com/hotel/fr/chalet-les-pr...
12,LE CANGE,Amiens,9.4,https://www.booking.com/hotel/fr/le-cange.fr.h...
13,"Le Logis du Moulin Gîte avec Jacuzzi, à 800m d...",Carcassonne,9.4,https://www.booking.com/hotel/fr/le-logis-du-m...
14,Grand Hotel de Courtoisville,St Malo,9.4,https://www.booking.com/hotel/fr/grand-de-cour...
15,L'Emeraude,St Malo,9.4,https://www.booking.com/hotel/fr/l-39-emeraude...
16,Appartement confortable et élégant en centre v...,Rouen,9.3,https://www.booking.com/hotel/fr/appartement-c...
17,Villa Maélie,Uzes,9.3,https://www.booking.com/hotel/fr/villa-maelie....
18,Appartements Residilaverde Gare,Grenoble,9.3,https://www.booking.com/hotel/fr/residilaverde...
19,Maison Albar Hotels L’Imperator,Nimes,9.2,https://www.booking.com/hotel/fr/imperator-nim...
20,"Coutelon, havre de paix en pleine nature",Gorges du Verdon,9.2,https://www.booking.com/hotel/fr/coutelon.fr.h...

## 9. Conformite au RGPD

Le processus de collecte a ete concu dans le respect du Reglement General sur la Protection des Donnees.

- **Absence de donnees personnelles.** Le projet ne collecte aucune donnee relative a une personne physique identifiee ou identifiable. Les donnees traitees sont des informations publiques et non nominatives : coordonnees geographiques de villes, previsions meteorologiques, et fiches d'etablissements hoteliers (nom commercial, note agregee, description, lien). Les avis individuels et les noms d'utilisateurs ne sont ni collectes ni stockes.

- **Minimisation des donnees.** Seuls les champs strictement necessaires a la recommandation sont conserves (ville, coordonnees, temperature, probabilite de pluie, note moyenne des hotels). Aucune donnee superflue n'est extraite.

- **Securite des secrets.** Les cles d'API (OpenWeatherMap) et les identifiants AWS (S3, RDS) ne figurent jamais en clair dans le code. Ils sont charges depuis des fichiers `.env` exclus du versionnement par le fichier `.gitignore`. Seuls des fichiers d'exemple (`openweather.exemple`, `aws.env.example`) sont publies.

- **Sources et conditions d'utilisation.** Les donnees meteo proviennent d'une API publique utilisee dans le cadre de ses conditions. Le scraping de Booking.com se limite a des informations publiquement affichees, avec des cadences d'appel raisonnables (pauses entre requetes) afin de ne pas surcharger le service.

- **Stockage maitrise.** Les donnees sont hebergees sur une infrastructure AWS dont l'acces est restreint (identifiants dedies, groupe de securite RDS limitant les adresses IP autorisees).

## 10. Conclusion

Ce projet met en oeuvre un pipeline ETL complet :

| Etape | Technologie |
|---|---|
| Geocodage des villes et des hotels | Nominatim (OpenStreetMap) |
| Donnees meteo (agregees sur l'horizon de prevision) | API OpenWeatherMap |
| Scraping hotels | Selenium + BeautifulSoup |
| Stockage brut | AWS S3 (Data Lake) |
| Stockage structure | AWS RDS / PostgreSQL (Data Warehouse) |
| Visualisation | Plotly Express (Mapbox) |

**Pistes d'amelioration :** automatisation hebdomadaire via AWS Lambda + enrichissement avec les prix des billets de train (API SNCF) pour un score de voyage plus complet.