In [1]:
import pandas as pd
import numpy as np
import random
import json
import tqdm

In [2]:
pd.options.display.max_columns = None

In [14]:
dataset = pd.read_csv("./CheXpert/df_chexpert_plus_240401.csv")
dataset = dataset.sort_values(by="path_to_image", ignore_index=True)
columns_keep = ['path_to_image', 'deid_patient_id', 'report', 'section_findings', 'section_impression', 'section_summary']
dataset = dataset[columns_keep]
dataset

,path_to_image,deid_patient_id,report,section_findings,section_impression,section_summary
0,train/patient00001/study1/view1_frontal.jpg,patient00001,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\n \nLeft subclavian central venous catheter w...,\n \n1. Left subclavian central venous cathet...,NaN
1,train/patient00002/study1/view1_frontal.jpg,patient00002,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,\nThere is severe kyphosis centered at the mid...,\n1. MARKED KYPHOSIS WITH STATUS POST VERTEBRO...,"4: Possible Significant Abnormality/Change, m..."
2,train/patient00002/study1/view2_lateral.jpg,patient00002,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,\nThere is severe kyphosis centered at the mid...,\n1. MARKED KYPHOSIS WITH STATUS POST VERTEBRO...,"4: Possible Significant Abnormality/Change, m..."
3,train/patient00002/study2/view1_frontal.jpg,patient00002,"NARRATIVE:\nSINGLE VIEW OF THE CHEST, 4 VIEWS ...",NaN,\n1. SINGLE SUPINE PORTABLE FRONTAL VIEW OF TH...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
4,train/patient00003/study1/view1_frontal.jpg,patient00003,"NARRATIVE:\nCHEST, ONE VIEW: 2-10-2001\nFINDIN...","Costophrenic angles sharp, without evidence o...",\n1. NO EVIDENCE OF PNEUMOTHORAX.\n2. MILD INT...,2\nI have personally reviewed the images for ...
...,...,...,...,...,...,...
223457,valid/patient64736/study1/view1_frontal.jpg,patient64736,NARRATIVE:\nChest 1 View: 9/6/2003\n \nHISTORY...,NaN,\n \n1.THERE IS FREE INTRAPERITONEAL AIR SEEN...,"4-POSSIBLY SIGNIFICANT FINDING, MAY NEED ACTIO..."
223458,valid/patient64737/study1/view1_frontal.jpg,patient64737,NARRATIVE:\nPORTABLE CHEST RADIOGRAPH 1 VIEW: ...,NaN,\n1. INTERVAL REMOVAL OF RIGHT SUBCLAVIAN CENT...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
223459,valid/patient64738/study1/view1_frontal.jpg,patient64738,"NARRATIVE:\nChest 1 View, april 21\n \nHISTORY...",NaN,\n \n1.INTERVAL PLACEMENT OF A LEFT UPPER EX...,"2-ABNORMAL, PREVIOUSLY REPORTED\nI have perso..."
223460,valid/patient64739/study1/view1_frontal.jpg,patient64739,NARRATIVE:\nCOMPARISON: 7-21-2005\n \nIMPRESSI...,NaN,\n \nCARDIAC SILHOUETTE REMAINS MILDLY ENLARGE...,"2-ABNORMAL, PREVIOUSLY REPORTED\n \n"
223461,valid/patient64740/study1/view1_frontal.jpg,patient64740,NARRATIVE:\n SINGLE VIEW OF CHEST: 7/9/2017\n...,NaN,\n1. THERE HAS BEEN INTERVAL INCREASE ...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."

In [ ]:
sub_dataset = dataset.groupby(by="deid_patient_id").sample()

In [16]:
sub_dataset

,path_to_image,deid_patient_id,report,section_findings,section_impression,section_summary
0,train/patient00001/study1/view1_frontal.jpg,patient00001,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\n \nLeft subclavian central venous catheter w...,\n \n1. Left subclavian central venous cathet...,NaN
1,train/patient00002/study1/view1_frontal.jpg,patient00002,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,\nThere is severe kyphosis centered at the mid...,\n1. MARKED KYPHOSIS WITH STATUS POST VERTEBRO...,"4: Possible Significant Abnormality/Change, m..."
4,train/patient00003/study1/view1_frontal.jpg,patient00003,"NARRATIVE:\nCHEST, ONE VIEW: 2-10-2001\nFINDIN...","Costophrenic angles sharp, without evidence o...",\n1. NO EVIDENCE OF PNEUMOTHORAX.\n2. MILD INT...,2\nI have personally reviewed the images for ...
5,train/patient00004/study1/view1_frontal.jpg,patient00004,"NARRATIVE:\nChest 2 Views, 6/6/2014\n \nHISTOR...",NaN,\n \n1.TWO VIEWS OF THE CHEST DEMONSTRATE A ...,1-NO SIGNIFICANT ABNORMALITY\nI have personal...
10,train/patient00005/study2/view2_frontal.jpg,patient00005,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\n \nUnchanged tunneled left internal jugular ...,\n \n1. Moderate left apical pneumothorax.\n ...,NaN
...,...,...,...,...,...,...
223457,valid/patient64736/study1/view1_frontal.jpg,patient64736,NARRATIVE:\nChest 1 View: 9/6/2003\n \nHISTORY...,NaN,\n \n1.THERE IS FREE INTRAPERITONEAL AIR SEEN...,"4-POSSIBLY SIGNIFICANT FINDING, MAY NEED ACTIO..."
223458,valid/patient64737/study1/view1_frontal.jpg,patient64737,NARRATIVE:\nPORTABLE CHEST RADIOGRAPH 1 VIEW: ...,NaN,\n1. INTERVAL REMOVAL OF RIGHT SUBCLAVIAN CENT...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
223459,valid/patient64738/study1/view1_frontal.jpg,patient64738,"NARRATIVE:\nChest 1 View, april 21\n \nHISTORY...",NaN,\n \n1.INTERVAL PLACEMENT OF A LEFT UPPER EX...,"2-ABNORMAL, PREVIOUSLY REPORTED\nI have perso..."
223460,valid/patient64739/study1/view1_frontal.jpg,patient64739,NARRATIVE:\nCOMPARISON: 7-21-2005\n \nIMPRESSI...,NaN,\n \nCARDIAC SILHOUETTE REMAINS MILDLY ENLARGE...,"2-ABNORMAL, PREVIOUSLY REPORTED\n \n"
223461,valid/patient64740/study1/view1_frontal.jpg,patient64740,NARRATIVE:\n SINGLE VIEW OF CHEST: 7/9/2017\n...,NaN,\n1. THERE HAS BEEN INTERVAL INCREASE ...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."

In [6]:
SAMPLE_SIZE = 20000

In [39]:
df_pos = sub_dataset.sample(SAMPLE_SIZE, random_state=42)
df_pos

,path_to_image,deid_patient_id,report,section_findings,section_impression,section_summary
85986,train/patient20638/study1/view1_frontal.jpg,patient20638,"NARRATIVE:\nEXAM: Chest 1 View August 9th, 200...",NaN,\n \n1.PORTABLE RADIOGRAPH OF THE CHEST DEMONS...,"4-POSSIBLY SIGNIFICANT FINDING, MAY NEED ACTIO..."
4079,train/patient01004/study1/view1_frontal.jpg,patient01004,NARRATIVE:\nChest 2 Views 12-19-2017\n \nHisto...,PA and lateral view of the chest demonstrate...,\n \nPROBABLE SMALL LEFT RETROCARDIAC POSTER...,1-NO SIGNIFICANT ABNORMALITY\n \n
214718,train/patient58143/study1/view1_frontal.jpg,patient58143,NARRATIVE:\nPORTABLE CHEST: 7/30/09\nCLINICAL...,NaN,\n 1. RIGHT INTERNAL JUGULAR CENTRAL LINE ...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
578,train/patient00145/study1/view1_frontal.jpg,patient00145,"NARRATIVE:\nExam: Chest 2 Views, 7-30-2017\n \...",NaN,\n \n1.TWO VIEWS OF THE CHEST DEMONSTRATE CARD...,"4-POSSIBLY SIGNIFICANT FINDING, MAY NEED ACTIO..."
20878,train/patient05116/study8/view1_frontal.jpg,patient05116,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,NaN,\n \n1. Post surgical changes of lung transpl...,NaN
...,...,...,...,...,...,...
58746,train/patient14233/study3/view1_frontal.jpg,patient14233,NARRATIVE:\nEXAM: Chest 1 View 7/21/2008\n \nC...,NaN,\n \n1.INITIAL CHEST RADIOGRAPH DEMONSTRATES S...,"4-POSSIBLY SIGNIFICANT FINDING, MAY NEED ACTIO..."
206588,train/patient53101/study1/view1_frontal.jpg,patient53101,"NARRATIVE:\nCHEST: One view chest, 03/14/20 53...",\nThere are low lung volumes with indistinct p...,\n1. MILD INTERSTITIAL PULMONARY EDEMA.\n2. MI...,"4: POSSIBLE SIGNIFICANT FINDINGS, MAY NEED AC..."
221230,train/patient62732/study1/view1_frontal.jpg,patient62732,NARRATIVE:\nSINGLE FRONTAL VIEW OF THE CHEST: ...,The left lung base is not well evaluated due...,\n \n 1. MILD INTERSTITIAL EDEMA AND CARDIOM...,"2-ABNORMAL, PREVIOUSLY REPORTED\n \n"
1252,train/patient00300/study1/view1_frontal.jpg,patient00300,"NARRATIVE:\nEXAM: Chest 1 View, 21/5/07\n \nCL...",NaN,\n \n1.TRAUMA RADIOGRAPH OF THE CHEST DEMONSTR...,1-NO SIGNIFICANT ABNORMALITY\nI have personall...
130382,train/patient31256/study9/view1_frontal.jpg,patient31256,NARRATIVE:\nChest 1 View Portable 8/27/17\n \n...,NaN,\n \n1. LIMITED AP LORDOTIC PORTABLE VIEW OF ...,"4-POSSIBLY SIGNIFICANT FINDING, MAY NEED ACTIO..."

In [ ]:
df_pos.to_csv("./chexpert_matches_sample.csv")

In [40]:
df_neg = sub_dataset.drop(index=df_pos.index).sample(SAMPLE_SIZE, random_state=42)
df_neg

,path_to_image,deid_patient_id,report,section_findings,section_impression,section_summary
213959,train/patient57681/study1/view1_frontal.jpg,patient57681,"NARRATIVE:\nCHEST: 8/17/2004, 19:21\n \n COMP...",Interval substantial decrease in the right p...,\n \n 1. INTERVAL DECREASE IN RIGHT-SIDED PL...,"2-ABNORMAL, PREVIOUSLY REPORTED \nI have per..."
221631,train/patient63093/study1/view1_frontal.jpg,patient63093,NARRATIVE:\nPORTABLE CHEST: 6/24/2011 \n \n ...,\n \n Single frontal view of the chest agai...,\n \n 1. LEFT SUBCLAVIAN LINE WITHOUT EVIDE...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
130102,train/patient31182/study1/view1_frontal.jpg,patient31182,NARRATIVE:\nCOMPARISON: 10/4/2015\n \nCLINICA...,NaN,\n \n1. SINGLE UPRIGHT AP VIEW OF THE CHEST D...,"2-ABNORMAL, PREVIOUSLY REPORTED\nI have person..."
87106,train/patient20936/study2/view1_frontal.jpg,patient20936,NARRATIVE:\nAP SINGLE VIEW OF THE CHEST: 5/27/...,NaN,"\nTHERE ARE BIBASILAR OPACITIES, WHICH LIKELY ...","2 ABNORMAL, PREVIOUSLY REPORTED.\nI have pers..."
41411,train/patient10146/study1/view1_frontal.jpg,patient10146,"NARRATIVE:\nCHEST, ONE VIEW: 12-7-2010.\nIMPRE...",NaN,\n1. AP PORTABLE CHEST WITHOUT COMPARISONS DEM...,"2 ABNORMAL, PREVIOUSLY REPORTED\n \n"
...,...,...,...,...,...,...
156387,train/patient36688/study4/view1_frontal.jpg,patient36688,NARRATIVE:\nCHEST 1 VIEW PORTABLE: 2/1/2004\nH...,/,\n1. INTERVAL REMOVAL OF RIGHT INTERNAL JUGULA...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
137781,train/patient33124/study1/view1_frontal.jpg,patient33124,NARRATIVE:\nCHEST AP PROJECTION: 3/23/2007\nCO...,The tip of the PICC line is near the cavoatri...,\n1. POST PICC LINE PLACEMENT. LEFT PLEURAL EF...,"4 POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACT..."
167241,train/patient39067/study2/view1_frontal.jpg,patient39067,"NARRATIVE:\nEXAM: Chest 1 View, 04-12.\n \nHIS...",NaN,\n \n1.SUPPORT TUBES AND LINES IN APPROPRIATE ...,"2-ABNORMAL, PREVIOUSLY REPORTED\nI have person..."
32598,train/patient07956/study1/view1_frontal.jpg,patient07956,"NARRATIVE:\nEXAM: Chest 1 View, 08-13-2018\n \...",NaN,\n \n1.THERE IS RIGHT LOWER LOBE COLLAPSE VERS...,"4-POSSIBLE SIGNIFICANT FINDING, MAY NEED ACTI..."
133757,train/patient32124/study1/view2_lateral.jpg,patient32124,"NARRATIVE:\nChest two views, 4/21/17\n \nHISTO...",NaN,\n \nTHE LUNGS ARE CLEAR WITHOUT FOCAL INFIL...,1-NO SIGNIFICANT ABNORMALITY\nI have personal...

In [19]:
df_build_neg = dataset.drop(index=df_pos.index)
df_build_neg

,path_to_image,deid_patient_id,report,section_findings,section_impression,section_summary
0,train/patient00001/study1/view1_frontal.jpg,patient00001,NARRATIVE:\nRADIOGRAPHIC EXAMINATION OF THE CH...,\n \nLeft subclavian central venous catheter w...,\n \n1. Left subclavian central venous cathet...,NaN
2,train/patient00002/study1/view2_lateral.jpg,patient00002,NARRATIVE:\nFRONTAL AND LATERAL CHEST RADIOGRA...,\nThere is severe kyphosis centered at the mid...,\n1. MARKED KYPHOSIS WITH STATUS POST VERTEBRO...,"4: Possible Significant Abnormality/Change, m..."
3,train/patient00002/study2/view1_frontal.jpg,patient00002,"NARRATIVE:\nSINGLE VIEW OF THE CHEST, 4 VIEWS ...",NaN,\n1. SINGLE SUPINE PORTABLE FRONTAL VIEW OF TH...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
4,train/patient00003/study1/view1_frontal.jpg,patient00003,"NARRATIVE:\nCHEST, ONE VIEW: 2-10-2001\nFINDIN...","Costophrenic angles sharp, without evidence o...",\n1. NO EVIDENCE OF PNEUMOTHORAX.\n2. MILD INT...,2\nI have personally reviewed the images for ...
5,train/patient00004/study1/view1_frontal.jpg,patient00004,"NARRATIVE:\nChest 2 Views, 6/6/2014\n \nHISTOR...",NaN,\n \n1.TWO VIEWS OF THE CHEST DEMONSTRATE A ...,1-NO SIGNIFICANT ABNORMALITY\nI have personal...
...,...,...,...,...,...,...
223456,valid/patient64735/study1/view1_frontal.jpg,patient64735,NARRATIVE:\nAP PORTABLE SEMIUPRIGHT CHEST: 6/...,NaN,\n \n PATCHY LIMITED ATELECTASIS AND/OR CONSO...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
223457,valid/patient64736/study1/view1_frontal.jpg,patient64736,NARRATIVE:\nChest 1 View: 9/6/2003\n \nHISTORY...,NaN,\n \n1.THERE IS FREE INTRAPERITONEAL AIR SEEN...,"4-POSSIBLY SIGNIFICANT FINDING, MAY NEED ACTIO..."
223458,valid/patient64737/study1/view1_frontal.jpg,patient64737,NARRATIVE:\nPORTABLE CHEST RADIOGRAPH 1 VIEW: ...,NaN,\n1. INTERVAL REMOVAL OF RIGHT SUBCLAVIAN CENT...,"4-POSSIBLE SIGNIFICANT FINDINGS, MAY NEED ACTI..."
223459,valid/patient64738/study1/view1_frontal.jpg,patient64738,"NARRATIVE:\nChest 1 View, april 21\n \nHISTORY...",NaN,\n \n1.INTERVAL PLACEMENT OF A LEFT UPPER EX...,"2-ABNORMAL, PREVIOUSLY REPORTED\nI have perso..."
223460,valid/patient64739/study1/view1_frontal.jpg,patient64739,NARRATIVE:\nCOMPARISON: 7-21-2005\n \nIMPRESSI...,NaN,\n \nCARDIAC SILHOUETTE REMAINS MILDLY ENLARGE...,"2-ABNORMAL, PREVIOUSLY REPORTED\n \n"

In [20]:
impression = pd.read_json("./CheXpert/chexbert_labels/impression_fixed.json", lines=True)
impression = impression.sort_values(by="path_to_image", ignore_index=True)
impression

,path_to_image,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,No Finding
0,train/patient00001/study1/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.0,1.0
1,train/patient00002/study1/view1_frontal.jpg,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
2,train/patient00002/study1/view2_lateral.jpg,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
3,train/patient00002/study2/view1_frontal.jpg,NaN,1.0,1.0,NaN,-1.0,-1.0,NaN,-1.0,NaN,-1.0,NaN,1.0,NaN,NaN
4,train/patient00003/study1/view1_frontal.jpg,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223457,valid/patient64736/study1/view1_frontal.jpg,NaN,0.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,1.0,NaN
223458,valid/patient64737/study1/view1_frontal.jpg,-1.0,NaN,1.0,NaN,NaN,-1.0,NaN,-1.0,0.0,NaN,NaN,NaN,1.0,NaN
223459,valid/patient64738/study1/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
223460,valid/patient64739/study1/view1_frontal.jpg,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
223461,valid/patient64740/study1/view1_frontal.jpg,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN

In [21]:
impression = impression.fillna(3)
impression

,path_to_image,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,No Finding
0,train/patient00001/study1/view1_frontal.jpg,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,1.0,1.0
1,train/patient00002/study1/view1_frontal.jpg,3.0,3.0,1.0,3.0,3.0,-1.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0
2,train/patient00002/study1/view2_lateral.jpg,3.0,3.0,1.0,3.0,3.0,-1.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0
3,train/patient00002/study2/view1_frontal.jpg,3.0,1.0,1.0,3.0,-1.0,-1.0,3.0,-1.0,3.0,-1.0,3.0,1.0,3.0,3.0
4,train/patient00003/study1/view1_frontal.jpg,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223457,valid/patient64736/study1/view1_frontal.jpg,3.0,0.0,3.0,3.0,1.0,0.0,3.0,3.0,3.0,0.0,3.0,3.0,1.0,3.0
223458,valid/patient64737/study1/view1_frontal.jpg,-1.0,3.0,1.0,3.0,3.0,-1.0,3.0,-1.0,0.0,3.0,3.0,3.0,1.0,3.0
223459,valid/patient64738/study1/view1_frontal.jpg,3.0,3.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0
223460,valid/patient64739/study1/view1_frontal.jpg,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0
223461,valid/patient64740/study1/view1_frontal.jpg,1.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,1.0,3.0,3.0

In [22]:
df_neg = df_neg.merge(right=impression, on="path_to_image")
df_build_neg = df_build_neg.merge(right=impression, on="path_to_image")

In [30]:
def generate_balanced_mismatch(df_neg, df_build_neg, total_samples=SAMPLE_SIZE):
    """
    - 50% of total mismatches with no pathology in common (1 vs 0)
    - 30% of partial mismatches with no ambiguity (at least one 1 vs 0 + no 1 vs Nan or -1)
    - 20% of partial mismatches (at least 1 vs 0)
    """
    
    # Reset indices to ensure positional alignment with matrices
    df_neg = df_neg.reset_index(drop=True)
    df_build_neg = df_build_neg.reset_index(drop=True)
    
    # Don't take into account "Support Devices" and "No Finding"
    pure_pathologies = [
            'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity', 'Lung Lesion', 'Edema', 'Consolidation',
            'Pneumonia', 'Atelectasis', 'Pneumothorax', 'Pleural Effusion', 'Pleural Other', 'Fracture'
        ]
    
    # Convert dataframes into matrices, focus on phatologies columns
    matrix_neg = df_neg[pure_pathologies].values
    #matrix_build_neg = df_build_neg[pure_pathologies].values
    
    # Quotas definition
    quotas = {
        "Total": int(total_samples * 0.50),
        "Solid": int(total_samples * 0.30),
        "Easy": int(total_samples * 0.20)
    }
    counts = {"Total": 0, "Solid": 0, "Easy": 0}
    # Storage for rows that successfully become verified mismatches
    mismatch_rows = []
    #len_j = len(df_build_neg)

    for i in range(len(matrix_neg)):
        # Early exit if we have completely filled all quotas
        if sum(counts.values()) >= total_samples:
            break
        
        matrix_build_neg = df_build_neg[pure_pathologies].values
        len_j = len(df_build_neg)
        vec_i = matrix_neg[i]
        pos_i = (vec_i == 1)
        
        # Randomly select the start index in the matrix where to look for mismatches
        start_j = random.randint(0, len_j - 1)
        
        for offset in range(len_j):
            j = (start_j + offset) % len_j
                
            vec_j = matrix_build_neg[j]
            pos_j = (vec_j == 1)
            
            # Total mismatch
            total_i_to_j = np.all(vec_j[pos_i] == 0) if np.any(pos_i) else True
            total_j_to_i = np.all(vec_i[pos_j] == 0) if np.any(pos_j) else True
            is_total = total_i_to_j and total_j_to_i and (np.any(pos_i) or np.any(pos_j))
            # At least one clear differnce of one pathology
            has_diff = np.any((vec_i == 1) & (vec_j == 0)) or np.any((vec_j == 1) & (vec_i == 0))
            # Some ambiguity: 1 vs NaN(3) or -1. NaN=not written, -1=Uncertain
            has_ambiguity = np.any((vec_i == 1) & np.isin(vec_j, [-1, 3])) or np.any((vec_j == 1) & np.isin(vec_i, [-1, 3]))
            
            # Type of the mismatch
            pair_type = None
            if is_total:
                pair_type = "Total"
            elif has_diff and not has_ambiguity:
                pair_type = "Solid"
            elif has_diff and has_ambiguity:
                pair_type = "Easy"
                
            # Si la paire entre dans un quota non rempli, on la sauvegarde
            if pair_type and counts[pair_type] < quotas[pair_type]:
                # Extract base image data from row i, swap text fields from row j
                row_data = df_neg.iloc[i].copy()
                row_data["report"] = df_build_neg.loc[j, "report"]
                row_data["section_findings"] = df_build_neg.loc[j, "section_findings"]
                row_data["section_impression"] = df_build_neg.loc[j, "section_impression"]
                row_data["section_summary"] = df_build_neg.loc[j, "section_summary"]
                row_data["mismatch_tier"] = pair_type

                df_build_neg = df_build_neg.drop(index=j).reset_index(drop=True)
                print(i, pair_type)
                mismatch_rows.append(row_data)
                counts[pair_type] += 1
                break

    # Build final clean dataframe from collected rows
    result_df = pd.DataFrame(mismatch_rows).reset_index(drop=True)
    print("Generation Successful! Sub-distribution counts:")
    for k, v in counts.items():
        print(f"  {k}: {v}")
    return result_df

In [ ]:
df_result_neg = generate_balanced_mismatch(df_neg, df_build_neg)

0 Easy
1 Easy
2 Total
3 Easy
4 Easy
5 Easy
6 Easy
7 Easy
8 Easy
9 Easy
11 Total
12 Easy
13 Easy
14 Easy
15 Easy
16 Total
17 Easy
18 Total
19 Total
20 Easy
21 Easy
22 Easy
23 Easy
24 Easy
25 Easy
26 Total
27 Easy
28 Easy
29 Easy
30 Total
31 Easy
32 Easy
33 Easy
34 Easy
35 Easy
36 Easy
37 Total
38 Easy
39 Easy
40 Easy
41 Easy
42 Easy
43 Easy
44 Easy
45 Total
46 Easy
47 Easy
48 Easy
49 Easy
50 Easy
51 Easy
52 Total
53 Easy
54 Total
55 Easy
56 Solid
57 Easy
58 Easy
59 Easy
60 Easy
61 Easy
62 Easy
63 Easy
64 Easy
65 Easy
66 Easy
67 Easy
68 Easy
69 Easy
70 Easy
71 Easy
72 Easy
73 Easy
74 Solid
75 Total
76 Easy
77 Total
78 Easy
79 Easy
80 Easy
81 Easy
82 Easy
83 Easy
84 Easy
85 Easy
86 Easy
87 Solid
88 Easy
89 Easy
90 Easy
91 Easy
92 Easy
93 Easy
94 Easy
95 Easy
96 Total
97 Easy
98 Easy
99 Easy
100 Easy
101 Easy
102 Easy
103 Total
104 Easy
105 Easy
106 Total
107 Easy
108 Easy
109 Easy
110 Easy
111 Easy
112 Easy
113 Easy
114 Easy
115 Easy
116 Total
117 Easy
118 Easy
119 Easy
120 Easy
121 Easy
122 Easy
123 Easy
124 Easy
125 Easy
126 Easy
127 Easy
128 Easy
129 Easy
130 Easy
131 Easy
132 Easy
133 Easy
134 Total
135 Total
136 Easy
137 Easy
138 Easy
139 Easy
140 Easy
141 Total
142 Easy
143 Solid
144 Total
145 Easy
146 Total
147 Easy
148 Easy
149 Total
150 Solid
151 Easy
152 Total
153 Easy
154 Easy
155 Easy
156 Easy
157 Easy
158 Total
159 Easy
160 Easy
161 Easy
162 Easy
163 Easy
164 Total
165 Easy
166 Easy
168 Easy
169 Easy
170 Total
171 Total
172 Easy
173 Easy
174 Easy
175 Solid
176 Total
177 Total
178 Easy
179 Total
180 Easy
181 Easy
182 Total
183 Easy
184 Easy
185 Easy
186 Easy
187 Easy
188 Total
189 Easy
190 Easy
191 Easy
192 Easy
193 Easy
194 Easy
196 Easy
197 Easy
198 Easy
199 Total
200 Easy
201 Easy
202 Easy
203 Easy
204 Easy
205 Easy
206 Easy
207 Easy
208 Easy
209 Easy
210 Solid
211 Total
212 Easy
213 Total
214 Easy
215 Easy
216 Easy
217 Easy
218 Easy
219 Easy
220 Easy
221 Easy
222 Easy
223 Easy
224 Easy
225 Solid
226 Easy
227 Easy
228 Easy
229 Easy
230 Easy
231 Easy
232 Solid
233 Easy
234 Total
235 Easy
236 Total
237 Easy
238 Easy
239 Easy
240 Total
241 Easy
242 Total
243 Easy
244 Easy
245 Easy
246 Easy
247 Easy
248 Total
249 Easy
250 Total
251 Easy
252 Easy
253 Easy
254 Easy
255 Easy
256 Easy
257 Total
258 Easy
259 Easy
260 Easy
261 Easy
262 Total
263 Easy
264 Easy
265 Easy
266 Easy
267 Easy
268 Easy
269 Easy
270 Easy
271 Easy
272 Easy
273 Easy
274 Easy
275 Easy
276 Total
277 Easy
278 Easy
279 Total
280 Easy
281 Easy
282 Easy
283 Total
284 Easy
285 Easy
286 Easy
287 Easy
288 Total
289 Easy
290 Easy
291 Easy
292 Easy
293 Easy
294 Total
295 Easy
296 Easy
297 Easy
298 Easy
299 Total
300 Easy
301 Easy
302 Easy
303 Easy
304 Easy
305 Easy
306 Solid
307 Easy
308 Easy
309 Easy
310 Easy
311 Easy
312 Total
313 Total
314 Total
315 Easy
316 Easy
317 Easy
318 Easy
319 Easy
320 Easy
321 Easy
322 Easy
323 Easy
324 Easy
325 Easy
326 Easy
327 Easy
328 Easy
329 Easy
330 Easy
331 Easy
332 Easy
333 Easy
334 Easy
335 Easy
336 Easy
337 Easy
338 Easy
339 Easy
340 Easy
341 Easy
342 Easy
343 Total
344 Easy
345 Easy
346 Easy
347 Easy
348 Total
349 Easy
350 Easy
351 Easy
352 Easy
353 Easy
354 Total
355 Easy
356 Easy
357 Total
358 Total
359 Easy
360 Easy
361 Easy
362 Easy
363 Easy
364 Easy
365 Easy
366 Easy
367 Total
368 Easy
369 Easy
370 Easy
371 Easy
372 Easy
373 Total
374 Easy
375 Easy
376 Easy
377 Easy
378 Easy
379 Easy
380 Easy
381 Solid
382 Easy
383 Easy
384 Easy
385 Easy
386 Easy
387 Easy
388 Total
389 Easy
390 Easy
391 Solid
392 Easy
393 Total
394 Easy
395 Total
396 Easy
397 Easy
398 Easy
399 Easy
400 Total
401 Total
402 Easy
403 Easy
404 Total
405 Total
406 Total
407 Easy
408 Easy
409 Easy
410 Easy
411 Total
412 Easy
413 Easy
414 Easy
415 Easy
416 Easy
417 Easy
418 Total
419 Easy
420 Easy
421 Easy
422 Easy
423 Easy
424 Easy
425 Easy
426 Easy
427 Easy
428 Easy
429 Easy
430 Easy
431 Easy
432 Easy
433 Easy
434 Easy
435 Solid
436 Easy
437 Easy
438 Easy
439 Easy
440 Total
441 Easy
442 Easy
443 Easy
444 Easy
445 Easy
446 Easy
447 Total
448 Solid
449 Solid
450 Easy
451 Easy
452 Easy
453 Easy
454 Easy
455 Easy
456 Easy
457 Easy
458 Easy
459 Total
460 Easy
461 Easy
462 Easy
463 Easy
464 Easy
465 Easy
466 Easy
467 Easy
468 Easy
469 Easy
470 Easy
471 Easy
472 Easy
473 Total
474 Easy
475 Easy
476 Easy
477 Easy
478 Easy
479 Easy
480 Easy
481 Solid
482 Easy
483 Easy
484 Easy
485 Easy
486 Easy
487 Total
488 Easy
489 Easy
490 Easy
491 Total
492 Easy
493 Easy
494 Easy
495 Easy
496 Total
497 Easy
498 Easy
499 Solid
500 Easy
501 Total
502 Easy
503 Easy
504 Easy
505 Easy
506 Easy
507 Easy
508 Easy
509 Total
510 Easy
511 Easy
512 Easy
513 Easy
514 Easy
515 Easy
516 Easy
517 Solid
518 Total
520 Easy
521 Total
522 Easy
523 Easy
524 Easy
525 Easy
526 Easy
527 Easy
528 Easy
529 Total
530 Easy
531 Easy
532 Easy
533 Easy
534 Easy
535 Easy
536 Easy
537 Easy
539 Easy
540 Total
541 Easy
542 Easy
543 Easy
544 Easy
545 Total
546 Total
547 Solid
548 Easy
549 Easy
550 Easy
551 Easy
552 Total
553 Total
554 Easy
555 Easy
556 Easy
557 Easy
558 Easy
559 Easy
560 Easy
561 Easy
562 Easy
563 Easy
564 Total
565 Easy
566 Total
567 Easy
568 Total
569 Total
570 Solid
571 Solid
572 Easy
573 Easy
574 Easy
575 Easy
576 Easy
577 Solid
578 Easy
579 Easy
580 Easy
582 Easy
583 Easy
584 Easy
585 Easy
586 Easy
587 Easy
588 Easy
589 Easy
590 Easy
591 Easy
592 Easy
593 Easy
594 Total
595 Easy
596 Easy
597 Easy
598 Easy
599 Solid
600 Easy
601 Easy
602 Total
603 Easy
604 Easy
605 Easy
606 Total
607 Easy
608 Easy
609 Easy
610 Easy
611 Easy
612 Easy
613 Easy
614 Easy
615 Solid
616 Easy
617 Easy
618 Easy
619 Easy
621 Easy
622 Easy
623 Easy
624 Total
625 Easy
626 Easy
627 Easy
628 Easy
629 Total
630 Easy
631 Easy
632 Easy
633 Easy
634 Total
635 Easy
636 Easy
637 Easy
638 Easy
639 Easy
640 Easy
641 Easy
642 Easy
643 Easy
645 Easy
646 Easy
647 Easy
648 Easy
649 Easy
650 Total
651 Solid
652 Easy
653 Easy
654 Easy
655 Total
656 Easy
657 Easy
658 Easy
659 Total
660 Easy
661 Easy
662 Easy
663 Easy
664 Easy
665 Easy
666 Easy
667 Easy
668 Easy
669 Easy
670 Easy
671 Easy
672 Easy
673 Total
674 Easy
675 Easy
676 Easy
677 Solid
678 Easy
679 Easy
680 Solid
681 Easy
682 Easy
683 Easy
684 Easy
685 Easy
686 Easy
687 Easy
688 Easy
689 Easy
690 Total
692 Easy
693 Easy
694 Easy
695 Easy
696 Easy
697 Easy
698 Easy
699 Easy
700 Easy
701 Easy
702 Easy
703 Easy
704 Easy
705 Easy
706 Easy
707 Easy
708 Easy
709 Total
710 Easy
711 Easy
712 Easy
713 Easy
714 Easy
715 Easy
716 Total
717 Easy
718 Easy
719 Easy
720 Easy
722 Easy
723 Easy
725 Easy
726 Easy
727 Easy
728 Easy
729 Easy
730 Total
731 Easy
732 Easy
733 Solid
734 Easy
735 Easy
736 Total
737 Easy
738 Easy
739 Easy
740 Easy
741 Total
742 Easy
743 Easy
744 Easy
745 Easy
746 Easy
747 Easy
748 Easy
749 Easy
750 Total
751 Total
752 Easy
753 Total
754 Easy
755 Easy
756 Solid
757 Easy
758 Easy
759 Easy
760 Easy
761 Easy
762 Easy
763 Easy
764 Easy
765 Easy
766 Easy
767 Easy
768 Easy
769 Easy
770 Easy
771 Easy
772 Total
773 Easy
774 Total
775 Solid
776 Easy
777 Easy
778 Total
779 Easy
780 Easy
781 Easy
782 Solid
783 Easy
784 Solid
785 Easy
786 Easy
787 Easy
788 Easy
789 Easy
790 Easy
791 Easy
792 Easy
793 Easy
794 Easy
795 Easy
796 Easy
797 Total
798 Easy
799 Easy
800 Easy
801 Easy
802 Easy
803 Easy
804 Easy
805 Easy
806 Easy
807 Easy
808 Easy
809 Total
810 Easy
811 Easy
812 Total
814 Easy
815 Easy
816 Easy
817 Easy
818 Solid
819 Easy
821 Solid
822 Easy
823 Easy
824 Total
825 Easy
826 Easy
827 Easy
828 Easy
829 Total
830 Easy
831 Easy
832 Easy
833 Easy
834 Easy
835 Easy
836 Easy
837 Easy
838 Easy
839 Easy
840 Easy
841 Easy
842 Easy
843 Easy
844 Total
845 Easy
846 Easy
847 Easy
848 Total
849 Easy
850 Total
851 Easy
852 Easy
853 Easy
854 Easy
855 Easy
856 Easy
857 Easy
858 Easy
859 Easy
860 Easy
861 Easy
862 Easy
863 Easy
864 Easy
865 Easy
866 Easy
867 Easy
868 Easy
869 Easy
870 Easy
871 Easy
872 Easy
873 Easy
874 Easy
875 Easy
876 Easy
877 Easy
878 Easy
879 Easy
880 Total
881 Easy
882 Easy
883 Easy
884 Easy
885 Easy
886 Easy
887 Easy
888 Total
889 Total
890 Easy
891 Solid
892 Easy
893 Easy
894 Easy
895 Easy
896 Easy
897 Easy
898 Easy
899 Easy
900 Easy
901 Easy
902 Easy
905 Easy
906 Total
907 Easy
908 Easy
909 Easy
910 Easy
911 Solid
912 Easy
913 Total
914 Easy
915 Easy
916 Easy
917 Easy
918 Total
920 Easy
921 Solid
922 Easy
923 Easy
924 Easy
925 Total
926 Total
928 Easy
929 Easy
930 Easy
931 Easy
932 Easy
933 Easy
934 Easy
935 Easy
936 Easy
937 Easy
938 Easy
939 Easy
940 Easy
941 Solid
942 Easy
943 Easy
944 Easy
945 Easy
946 Easy
947 Easy
949 Easy
950 Easy
951 Total
952 Easy
953 Easy
954 Easy
955 Easy
956 Easy
957 Easy
958 Easy
959 Easy
960 Easy
961 Easy
962 Easy
963 Total
964 Total
965 Easy
966 Total
968 Solid
969 Easy
970 Easy
971 Easy
972 Easy
973 Easy
974 Easy
975 Easy
976 Easy
977 Easy
978 Easy
979 Total
980 Easy
981 Easy
982 Easy
983 Easy
984 Total
985 Total
986 Solid
987 Easy
988 Easy
989 Easy
990 Total
991 Easy
992 Total
993 Easy
994 Easy
995 Total
996 Easy
997 Easy
998 Easy
999 Easy
1000 Easy
1001 Easy
1002 Easy
1003 Easy
1004 Easy
1005 Easy
1006 Easy
1007 Easy
1008 Easy
1009 Easy
1010 Easy
1011 Total
1012 Easy
1013 Total
1014 Easy
1015 Solid
1016 Total
1017 Easy
1018 Easy
1019 Easy
1020 Easy
1021 Easy
1022 Easy
1023 Easy
1024 Easy
1025 Easy
1026 Easy
1027 Total
1028 Easy
1029 Easy
1030 Total
1031 Easy
1032 Easy
1033 Easy
1034 Easy
1035 Easy
1036 Solid
1037 Easy
1038 Easy
1039 Easy
1040 Total
1041 Easy
1042 Easy
1043 Easy
1044 Easy
1045 Total
1046 Easy
1047 Easy
1048 Easy
1049 Easy
1050 Easy
1051 Easy
1052 Easy
1053 Easy
1054 Total
1055 Easy
1056 Easy
1057 Easy
1058 Easy
1059 Easy
1060 Easy
1061 Easy
1062 Easy
1063 Easy
1064 Easy
1065 Easy
1066 Total
1067 Easy
1068 Easy
1069 Easy
1070 Easy
1071 Easy
1072 Easy
1073 Easy
1074 Total
1075 Easy
1076 Easy
1077 Easy
1078 Total
1079 Easy
1080 Solid
1082 Total
1083 Easy
1084 Easy
1085 Easy
1086 Easy
1087 Easy
1088 Easy
1089 Easy
1090 Easy
1091 Easy
1092 Easy
1093 Easy
1094 Easy
1095 Easy
1096 Total
1097 Easy
1098 Easy
1099 Total
1100 Easy
1101 Easy
1102 Easy
1103 Solid
1104 Easy
1105 Easy
1106 Easy
1107 Easy
1108 Easy
1109 Easy
1110 Easy
1111 Easy
1112 Easy
1113 Easy
1114 Easy
1115 Easy
1116 Easy
1117 Easy
1118 Easy
1119 Easy
1120 Easy
1121 Total
1122 Total
1123 Total
1124 Total
1125 Total
1126 Easy
1127 Easy
1128 Easy
1129 Easy
1130 Total
1131 Easy
1132 Easy
1133 Easy
1134 Easy
1135 Easy
1136 Easy
1137 Easy
1138 Easy
1139 Easy
1140 Easy
1141 Total
1142 Easy
1143 Easy
1144 Easy
1145 Easy
1146 Total
1147 Easy
1148 Easy
1149 Easy
1150 Easy
1151 Easy
1152 Easy
1153 Easy
1154 Easy
1155 Total
1156 Easy
1157 Total
1158 Easy
1159 Easy
1160 Easy
1161 Easy
1162 Easy
1163 Easy
1164 Total
1165 Easy
1166 Easy
1167 Solid
1168 Easy
1169 Easy
1170 Easy
1171 Easy
1172 Easy
1173 Easy
1174 Easy
1175 Easy
1176 Easy
1177 Easy
1178 Easy
1179 Easy
1180 Easy
1181 Total
1182 Easy
1183 Easy
1184 Easy
1185 Easy
1186 Easy
1187 Easy
1188 Total
1189 Total
1190 Total
1191 Easy
1192 Easy
1193 Easy
1194 Easy
1195 Easy
1196 Easy
1197 Easy
1198 Total
1199 Easy
1200 Easy
1201 Easy
1202 Total
1203 Easy
1204 Easy
1205 Easy
1206 Total
1207 Total
1208 Easy
1209 Easy
1210 Easy
1211 Easy
1212 Easy
1213 Easy
1214 Easy
1215 Easy
1216 Easy
1217 Easy
1218 Easy
1219 Easy
1220 Total
1221 Easy
1222 Easy
1223 Easy
1224 Easy
1225 Easy
1226 Easy
1227 Easy
1228 Easy
1229 Easy
1230 Easy
1231 Easy
1232 Easy
1233 Easy
1234 Total
1235 Easy
1236 Easy
1237 Easy
1238 Easy
1239 Easy
1240 Easy
1241 Easy
1242 Easy
1243 Easy
1244 Easy
1245 Total
1246 Easy
1247 Total
1248 Easy
1249 Easy
1250 Total
1251 Easy
1252 Easy
1253 Easy
1254 Total
1255 Easy
1256 Easy
1257 Easy
1258 Easy
1259 Easy
1260 Easy
1261 Easy
1262 Easy
1263 Easy
1264 Easy
1265 Easy
1266 Easy
1267 Easy
1268 Easy
1269 Easy
1270 Solid
1271 Easy
1272 Easy
1273 Easy
1274 Easy
1275 Total
1276 Easy
1277 Easy
1278 Easy
1279 Easy
1280 Easy
1281 Easy
1282 Total
1283 Easy
1284 Easy
1285 Easy
1286 Total
1287 Easy
1288 Easy
1289 Easy
1290 Easy
1291 Easy
1292 Easy
1293 Total
1294 Easy
1295 Total
1296 Easy
1297 Easy
1298 Easy
1299 Easy
1300 Easy
1301 Total
1302 Easy
1303 Total
1304 Easy
1305 Total
1306 Easy
1307 Easy
1308 Easy
1309 Easy
1310 Easy
1311 Total
1312 Easy
1313 Easy
1314 Easy
1315 Easy
1316 Easy
1317 Easy
1318 Easy
1319 Easy
1320 Easy
1321 Easy
1322 Easy
1323 Easy
1324 Easy
1325 Total
1326 Easy
1327 Easy
1328 Easy
1329 Easy
1330 Easy
1331 Easy
1332 Easy
1333 Easy
1334 Easy
1335 Easy
1336 Easy
1337 Easy
1338 Easy
1339 Easy
1340 Easy
1341 Easy
1342 Easy
1343 Easy
1344 Easy
1345 Total
1346 Easy
1347 Easy
1348 Easy
1349 Easy
1350 Easy
1351 Easy
1352 Easy
1353 Easy
1354 Easy
1355 Easy
1357 Easy
1358 Easy
1359 Easy
1360 Easy
1361 Total
1362 Easy
1363 Total
1364 Easy
1365 Easy
1366 Easy
1368 Easy
1369 Easy
1370 Total
1371 Easy
1372 Total
1373 Total
1374 Easy
1375 Total
1376 Easy
1377 Easy
1378 Easy
1379 Easy
1380 Easy
1381 Easy
1382 Easy
1383 Easy
1384 Easy
1385 Easy
1386 Easy
1387 Easy
1388 Solid
1389 Easy
1390 Total
1391 Easy
1392 Easy
1393 Easy
1394 Easy
1395 Easy
1396 Easy
1397 Easy
1398 Easy
1399 Total
1400 Easy
1401 Easy
1402 Easy
1403 Easy
1404 Easy
1405 Total
1406 Easy
1407 Easy
1408 Easy
1409 Solid
1410 Easy
1411 Solid
1412 Easy
1413 Easy
1414 Easy
1415 Total
1416 Easy
1417 Easy
1418 Easy
1419 Easy
1420 Easy
1421 Easy
1422 Easy
1423 Solid
1424 Easy
1425 Total
1426 Easy
1427 Easy
1428 Easy
1429 Easy
1430 Total
1431 Easy
1432 Easy
1433 Easy
1434 Total
1435 Easy
1436 Easy
1437 Easy
1438 Easy
1439 Easy
1440 Easy
1441 Solid
1442 Easy
1443 Easy
1444 Total
1445 Easy
1446 Easy
1447 Easy
1448 Easy
1449 Total
1450 Solid
1451 Easy
1452 Easy
1453 Easy
1454 Easy
1455 Easy
1456 Total
1457 Solid
1458 Easy
1459 Total
1460 Solid
1461 Easy
1462 Easy
1463 Easy
1464 Easy
1465 Easy
1466 Easy
1467 Easy
1469 Easy
1470 Easy
1471 Easy
1472 Easy
1473 Easy
1474 Easy
1475 Easy
1476 Easy
1477 Easy
1478 Easy
1479 Easy
1480 Easy
1481 Easy
1482 Easy
1483 Easy
1484 Easy
1485 Easy
1486 Total
1487 Easy
1488 Easy
1489 Easy
1490 Easy
1491 Total
1492 Easy
1493 Total
1494 Easy
1495 Easy
1496 Easy
1497 Solid
1498 Solid
1499 Total
1500 Solid
1501 Easy
1502 Easy
1503 Easy
1504 Easy
1505 Easy
1506 Easy
1507 Easy
1508 Total
1509 Easy
1510 Easy
1511 Easy
1512 Easy
1513 Easy
1514 Easy
1515 Easy
1516 Easy
1517 Easy
1518 Easy
1519 Total
1520 Easy
1521 Easy
1522 Easy
1523 Easy
1524 Easy
1525 Easy
1526 Total
1527 Easy
1528 Easy
1529 Easy
1530 Easy
1531 Easy
1532 Easy
1533 Easy
1534 Easy
1535 Easy
1536 Total
1537 Easy
1538 Total
1539 Solid
1540 Easy
1541 Easy
1542 Easy
1543 Easy
1544 Solid
1545 Solid
1546 Easy
1547 Easy
1548 Easy
1549 Solid
1550 Easy
1551 Easy
1552 Easy
1553 Easy
1554 Easy
1555 Easy
1556 Total
1557 Easy
1558 Easy
1559 Easy
1560 Easy
1561 Easy
1562 Easy
1563 Easy
1564 Easy
1565 Easy
1566 Total
1567 Easy
1568 Easy
1569 Easy
1570 Easy
1571 Easy
1572 Easy
1573 Easy
1574 Total
1575 Easy
1576 Easy
1577 Easy
1578 Easy
1579 Total
1580 Easy
1581 Easy
1582 Easy
1583 Easy
1584 Easy
1585 Easy
1586 Solid
1587 Easy
1588 Easy
1589 Easy
1590 Easy
1591 Total
1592 Easy
1593 Easy
1594 Easy
1595 Solid
1596 Easy
1597 Easy
1598 Easy
1599 Easy
1601 Easy
1602 Easy
1603 Easy
1604 Easy
1605 Easy
1606 Easy
1607 Easy
1608 Easy
1609 Easy
1610 Easy
1611 Easy
1612 Easy
1613 Easy
1614 Easy
1615 Easy
1616 Easy
1617 Easy
1618 Easy
1619 Easy
1620 Easy
1621 Easy
1622 Easy
1623 Solid
1624 Easy
1625 Easy
1626 Easy
1627 Solid
1628 Total
1629 Easy
1630 Easy
1631 Total
1632 Easy
1633 Easy
1634 Total
1635 Easy
1636 Easy
1637 Easy
1638 Solid
1639 Easy
1640 Easy
1641 Easy
1642 Easy
1643 Easy
1644 Easy
1645 Easy
1646 Easy
1647 Total
1648 Total
1649 Easy
1650 Easy
1651 Easy
1652 Easy
1653 Easy
1654 Easy
1655 Easy
1656 Easy
1657 Easy
1658 Easy
1659 Easy
1660 Easy
1662 Easy
1663 Easy
1664 Easy
1665 Easy
1666 Easy
1667 Easy
1668 Total
1669 Easy
1670 Easy
1671 Easy
1672 Easy
1673 Easy
1674 Easy
1675 Easy
1676 Easy
1677 Easy
1678 Easy
1679 Easy
1680 Easy
1681 Easy
1682 Easy
1683 Easy
1684 Total
1685 Easy
1686 Easy
1687 Easy
1688 Total
1689 Easy
1690 Easy
1691 Easy
1692 Easy
1693 Easy
1694 Easy
1695 Easy
1696 Total
1697 Easy
1698 Easy
1699 Easy
1700 Easy
1701 Easy
1702 Easy
1703 Easy
1704 Easy
1705 Easy
1706 Easy
1707 Easy
1708 Easy
1709 Total
1710 Easy
1711 Total
1712 Easy
1713 Total
1714 Easy
1715 Easy
1716 Easy
1717 Easy
1718 Total
1719 Easy
1720 Easy
1721 Easy
1722 Solid
1723 Easy
1724 Total
1725 Solid
1726 Solid
1727 Easy
1728 Easy
1729 Easy
1730 Easy
1731 Easy
1732 Easy
1733 Easy
1734 Easy
1735 Easy
1736 Easy
1737 Easy
1738 Easy
1739 Easy
1740 Solid
1741 Total
1743 Easy
1744 Easy
1745 Easy
1746 Solid
1747 Easy
1748 Easy
1749 Total
1750 Easy
1751 Easy
1752 Easy
1753 Easy
1754 Easy
1755 Easy
1756 Solid
1757 Solid
1758 Easy
1759 Total
1760 Easy
1761 Easy
1762 Easy
1763 Easy
1764 Easy
1765 Easy
1766 Easy
1767 Easy
1768 Easy
1769 Total
1770 Total
1771 Easy
1772 Easy
1773 Total
1774 Easy
1775 Total
1776 Easy
1777 Easy
1778 Easy
1779 Total
1780 Easy
1781 Easy
1782 Total
1783 Total
1784 Easy
1785 Easy
1786 Easy
1787 Easy
1788 Easy
1789 Easy
1790 Easy
1791 Easy
1792 Total
1793 Total
1794 Easy
1795 Easy
1796 Total
1797 Easy
1798 Easy
1799 Total
1800 Total
1801 Easy
1802 Total
1803 Easy
1804 Easy
1805 Easy
1806 Easy
1807 Easy
1808 Easy
1809 Easy
1810 Total
1811 Easy
1812 Easy
1813 Easy
1814 Easy
1815 Easy
1816 Easy
1817 Total
1818 Easy
1819 Easy
1820 Easy
1821 Easy
1822 Easy
1823 Easy
1824 Easy
1825 Easy
1826 Easy
1827 Easy
1828 Total
1829 Total
1830 Easy
1831 Easy
1832 Easy
1833 Easy
1834 Easy
1835 Easy
1836 Easy
1837 Easy
1838 Easy
1839 Easy
1840 Easy
1841 Easy
1842 Easy
1843 Easy
1844 Total
1845 Easy
1846 Total
1847 Total
1848 Easy
1849 Easy
1850 Total
1852 Easy
1853 Easy
1854 Easy
1855 Easy
1856 Easy
1857 Easy
1858 Easy
1859 Easy
1860 Easy
1861 Easy
1862 Easy
1863 Total
1864 Easy
1865 Easy
1866 Easy
1867 Easy
1868 Easy
1869 Easy
1870 Total
1871 Easy
1872 Total
1873 Easy
1874 Easy
1875 Easy
1876 Easy
1877 Easy
1878 Easy
1879 Easy
1880 Total
1881 Easy
1882 Easy
1883 Easy
1884 Easy
1885 Total
1886 Easy
1887 Total
1888 Easy
1890 Total
1891 Easy
1892 Easy
1893 Easy
1894 Easy
1895 Easy
1896 Easy
1897 Easy
1898 Easy
1899 Total
1900 Easy
1901 Easy
1902 Total
1903 Solid
1904 Total
1906 Easy
1907 Easy
1908 Easy
1909 Easy
1910 Easy
1911 Easy
1912 Easy
1913 Easy
1914 Total
1915 Easy
1916 Total
1917 Easy
1918 Total
1919 Total
1920 Easy
1921 Solid
1922 Easy
1923 Easy
1924 Easy
1925 Easy
1926 Solid
1927 Easy
1928 Total
1929 Easy
1930 Total
1931 Easy
1932 Easy
1933 Easy
1934 Easy
1935 Easy
1936 Easy
1937 Easy
1938 Easy
1939 Easy
1940 Easy
1941 Easy
1942 Easy
1943 Easy
1944 Easy
1945 Easy
1946 Total
1947 Easy
1948 Easy
1949 Easy
1950 Easy
1951 Easy
1952 Easy
1953 Easy
1954 Easy
1955 Easy
1956 Easy
1957 Easy
1958 Easy
1959 Total
1960 Easy
1961 Solid
1962 Easy
1963 Solid
1964 Total
1965 Total
1966 Easy
1967 Easy
1968 Easy
1969 Easy
1970 Easy
1971 Easy
1972 Easy
1973 Easy
1974 Easy
1975 Easy
1976 Easy
1977 Easy
1978 Easy
1979 Easy
1980 Total
1981 Solid
1982 Easy
1983 Easy
1984 Easy
1985 Easy
1986 Easy
1987 Easy
1988 Easy
1989 Easy
1990 Easy
1992 Easy
1993 Easy
1994 Easy
1995 Easy
1996 Easy
1997 Easy
1998 Easy
1999 Easy
2000 Total
2001 Easy
2002 Easy
2003 Easy
2004 Easy
2005 Easy
2006 Easy
2007 Easy
2008 Easy
2009 Total
2010 Easy
2011 Easy
2012 Easy
2013 Easy
2014 Easy
2015 Easy
2016 Easy
2017 Total
2018 Total
2019 Easy
2020 Easy
2021 Easy
2022 Total
2023 Easy
2024 Easy
2025 Total
2026 Easy
2027 Total
2028 Easy
2029 Solid
2030 Easy
2031 Easy
2032 Easy
2033 Easy
2034 Easy
2035 Easy
2036 Easy
2037 Easy
2038 Easy
2039 Easy
2040 Easy
2041 Easy
2042 Easy
2043 Easy
2044 Easy
2045 Easy
2046 Easy
2047 Total
2048 Easy
2049 Easy
2050 Easy
2051 Easy
2052 Easy
2053 Easy
2054 Easy
2055 Easy
2056 Easy
2057 Easy
2058 Easy
2059 Easy
2060 Easy
2061 Solid
2062 Easy
2063 Easy
2064 Easy
2065 Total
2066 Easy
2067 Easy
2068 Easy
2069 Easy
2070 Easy
2071 Easy
2072 Total
2073 Easy
2074 Total
2075 Easy
2076 Easy
2077 Easy
2078 Total
2080 Easy
2081 Solid
2082 Easy
2083 Easy
2085 Easy
2086 Easy
2087 Total
2088 Easy
2089 Easy
2090 Easy
2091 Easy
2092 Easy
2093 Easy
2094 Easy
2095 Easy
2096 Easy
2097 Easy
2098 Easy
2099 Solid
2100 Easy
2101 Easy
2102 Easy

In [ ]:
df_result_neg.to_csv("./chexpert_mismatches_swapping.csv")

In [42]:
for item in df_result_neg["report"]:
    if (item in df_neg["report"]) or (item in df_pos["report"]):
        print("Bad!!!")

In [23]:
def generate_cluster_balanced_mismatch(df_neg, df_build_neg, total_samples=SAMPLE_SIZE):
    df_neg = df_neg.reset_index(drop=True)
    df_build_neg = df_build_neg.reset_index(drop=True)
    
    pure_pathologies = [
        'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity', 'Lung Lesion', 
        'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis', 'Pneumothorax', 
        'Pleural Effusion', 'Pleural Other', 'Fracture'
    ]
    
    # Define clinical clusters mapping index positions to cluster groups
    # C1: Heart, C2: Opacities, C3: Pleural space, C4: Focal/Bone
    cluster_mapping = {
        0: 1, 1: 1,   # Enlarged Cardiomediastinum, Cardiomegaly
        2: 2, 4: 2, 5: 2, 6: 2, 7: 2,  # Lung Opacity, Edema, Consolidation, Pneumonia, Atelectasis
        8: 3, 9: 3, 10: 3, # Pneumothorax, Pleural Effusion, Pleural Other
        3: 4, 11: 4   # Lung Lesion, Fracture
    }
    
    matrix_neg = df_neg[pure_pathologies].values
    #matrix_build_neg = df_build_neg[pure_pathologies].values
    
    # Multi-dimensional sub-quotas
    quotas = {
        # Total (different cluster) 40%
        ("Total", "Diff"): int(total_samples * 0.4),
        # Solid (different cluster) 24%
        ("Solid", "Diff"): int(total_samples * 0.24),
        # Easy (different cluster) 16%
        ("Easy", "Diff"):  int(total_samples * 0.16),
        # Same clister whatever the type (Total or Solid or Easy) 20%
        ("All", "Same"): int(total_samples * 0.2)
    }
    
    counts = {k: 0 for k in quotas.keys()}
    mismatch_rows = []
    #len_j = len(df_build_neg)
    
    for i in range(len(matrix_neg)):
        if sum(counts.values()) >= total_samples:
            break
            
        matrix_build_neg = df_build_neg[pure_pathologies].values
        len_j = len(df_build_neg)
        vec_i = matrix_neg[i]
        pos_i = (vec_i == 1)
        
        start_j = random.randint(0, len_j - 1)
        
        for offset in range(len_j):
            j = (start_j + offset) % len_j
            
            vec_j = matrix_build_neg[j]
            pos_j = (vec_j == 1)
            
            total_i_to_j = np.all(vec_j[pos_i] == 0) if np.any(pos_i) else True
            total_j_to_i = np.all(vec_i[pos_j] == 0) if np.any(pos_j) else True
            is_total = total_i_to_j and total_j_to_i and (np.any(pos_i) or np.any(pos_j))
            has_diff = np.any((vec_i == 1) & (vec_j == 0)) or np.any((vec_j == 1) & (vec_i == 0))
            has_ambiguity = np.any((vec_i == 1) & np.isin(vec_j, [-1, 3])) or np.any((vec_j == 1) & np.isin(vec_i, [-1, 3]))
            
            tier_type = None
            if is_total:
                tier_type = "Total"
            elif has_diff and not has_ambiguity:
                tier_type = "Solid"
            elif has_diff and has_ambiguity:
                tier_type = "Easy"
                
            if not tier_type:
                continue  # Not a valid mismatch
                
            # --- Clustering Evaluation ---
            # Identify all pathologies present across BOTH individuals
            active_indices = np.where(((vec_i == 1) & (vec_j == 0)) | ((vec_i == 0) & (vec_j == 1)))[0]
            
            if len(active_indices) == 0:
                continue
                
            # Map those indices to their medical clusters
            active_clusters = set(cluster_mapping[idx] for idx in active_indices)
            
            # Determine if it's an intra-cluster (Same) or inter-cluster (Diff) mismatch
            cluster_type = "Same" if (len(active_clusters) == 1 and len(active_indices) != 1) else "Diff"
            if "Same" == cluster_type:
                tier_type = "All"
            
            # Composite Key lookup
            composite_key = (tier_type, cluster_type)
            
            # --- 3. Composite Quota Verification ---
            if counts[composite_key] < quotas[composite_key]:
                row_data = df_neg.iloc[i].copy()
                row_data["report"] = df_build_neg.loc[j, "report"]
                row_data["section_findings"] = df_build_neg.loc[j, "section_findings"]
                row_data["section_impression"] = df_build_neg.loc[j, "section_impression"]
                row_data["section_summary"] = df_build_neg.loc[j, "section_summary"]
                
                # Useful tracking tags for down-stream loss monitoring
                row_data["mismatch_tier"] = tier_type
                row_data["cluster_tier"] = cluster_type
                
                df_build_neg = df_build_neg.drop(index=j).reset_index(drop=True)
                mismatch_rows.append(row_data)
                counts[composite_key] += 1
                print(i, composite_key)
                break 

    result_df = pd.DataFrame(mismatch_rows).reset_index(drop=True)
    print("Generation Successful! Sub-distribution counts:")
    for k, v in counts.items():
        print(f"  {k}: {v}")
    return result_df

In [25]:
df_result_neg_cluster = generate_cluster_balanced_mismatch(df_neg, df_build_neg)

0 ('Easy', 'Diff')
1 ('Total', 'Diff')
2 ('Easy', 'Diff')
3 ('Total', 'Diff')
4 ('Easy', 'Diff')
5 ('Total', 'Diff')
6 ('Easy', 'Diff')
7 ('Easy', 'Diff')
8 ('Easy', 'Diff')
9 ('Easy', 'Diff')
11 ('Total', 'Diff')
12 ('Easy', 'Diff')
13 ('Total', 'Diff')
14 ('Easy', 'Diff')
15 ('Easy', 'Diff')
16 ('Total', 'Diff')
17 ('Total', 'Diff')
18 ('Total', 'Diff')
19 ('Easy', 'Diff')
20 ('Easy', 'Diff')
21 ('Easy', 'Diff')
22 ('Easy', 'Diff')
23 ('Easy', 'Diff')
24 ('Easy', 'Diff')
25 ('Easy', 'Diff')
26 ('Easy', 'Diff')
27 ('Easy', 'Diff')
28 ('Easy', 'Diff')
29 ('Easy', 'Diff')
30 ('Easy', 'Diff')
31 ('Easy', 'Diff')
32 ('Easy', 'Diff')
33 ('Easy', 'Diff')
34 ('Easy', 'Diff')
35 ('Easy', 'Diff')
36 ('Easy', 'Diff')
37 ('Easy', 'Diff')
38 ('Easy', 'Diff')
39 ('Easy', 'Diff')
40 ('Easy', 'Diff')
41 ('Easy', 'Diff')
42 ('Easy', 'Diff')
43 ('Easy', 'Diff')
44 ('Easy', 'Diff')
45 ('Easy', 'Diff')
46 ('Easy', 'Diff')
47 ('Easy', 'Diff')
48 ('Solid', 'Diff')
49 ('Easy', 'Diff')
50 ('Easy', 'Diff')
51 ('Easy', 'Diff')
52 ('Easy', 'Diff')
53 ('Easy', 'Diff')
54 ('Total', 'Diff')
55 ('Easy', 'Diff')
56 ('Easy', 'Diff')
57 ('Solid', 'Diff')
58 ('Easy', 'Diff')
59 ('Easy', 'Diff')
60 ('Easy', 'Diff')
61 ('Easy', 'Diff')
62 ('Solid', 'Diff')
63 ('Easy', 'Diff')
64 ('Easy', 'Diff')
65 ('Easy', 'Diff')
66 ('Easy', 'Diff')
67 ('Easy', 'Diff')
68 ('Easy', 'Diff')
69 ('Total', 'Diff')
70 ('Easy', 'Diff')
71 ('Easy', 'Diff')
72 ('Easy', 'Diff')
73 ('Easy', 'Diff')
74 ('Easy', 'Diff')
75 ('Easy', 'Diff')
76 ('Easy', 'Diff')
77 ('Total', 'Diff')
78 ('Total', 'Diff')
79 ('Total', 'Diff')
80 ('Easy', 'Diff')
81 ('Easy', 'Diff')
82 ('Easy', 'Diff')
83 ('Easy', 'Diff')
84 ('Easy', 'Diff')
85 ('Easy', 'Diff')
86 ('Easy', 'Diff')
87 ('Solid', 'Diff')
88 ('Easy', 'Diff')
89 ('Easy', 'Diff')
90 ('Easy', 'Diff')
91 ('Easy', 'Diff')
92 ('Easy', 'Diff')
93 ('Easy', 'Diff')
94 ('Easy', 'Diff')
95 ('Easy', 'Diff')
96 ('Total', 'Diff')
97 ('Easy', 'Diff')
98 ('Easy', 'Diff')
99 ('Easy', 'Diff')
100 ('Easy', 'Diff')
101 ('Easy', 'Diff')
102 ('Easy', 'Diff')
103 ('Easy', 'Diff')
104 ('Easy', 'Diff')
105 ('Easy', 'Diff')
106 ('Easy', 'Diff')
107 ('Easy', 'Diff')
108 ('Easy', 'Diff')
109 ('Easy', 'Diff')
110 ('Easy', 'Diff')
111 ('All', 'Same')
112 ('Solid', 'Diff')
113 ('Total', 'Diff')
114 ('Easy', 'Diff')
115 ('Easy', 'Diff')
116 ('Easy', 'Diff')
117 ('Total', 'Diff')
118 ('Easy', 'Diff')
119 ('Easy', 'Diff')
120 ('Easy', 'Diff')
121 ('Easy', 'Diff')
122 ('Easy', 'Diff')
123 ('Total', 'Diff')
124 ('Easy', 'Diff')
125 ('Easy', 'Diff')
126 ('Easy', 'Diff')
127 ('Easy', 'Diff')
128 ('Easy', 'Diff')
129 ('Easy', 'Diff')
130 ('Easy', 'Diff')
131 ('Easy', 'Diff')
132 ('Easy', 'Diff')
133 ('Easy', 'Diff')
134 ('Easy', 'Diff')
135 ('Total', 'Diff')
136 ('Easy', 'Diff')
137 ('Easy', 'Diff')
138 ('Easy', 'Diff')
139 ('Easy', 'Diff')
140 ('Easy', 'Diff')
141 ('Total', 'Diff')
142 ('Easy', 'Diff')
143 ('Easy', 'Diff')
144 ('Easy', 'Diff')
145 ('Easy', 'Diff')
146 ('Easy', 'Diff')
147 ('Easy', 'Diff')
148 ('Easy', 'Diff')
149 ('Easy', 'Diff')
150 ('Easy', 'Diff')
151 ('Easy', 'Diff')
152 ('Easy', 'Diff')
153 ('Easy', 'Diff')
154 ('Easy', 'Diff')
155 ('Easy', 'Diff')
156 ('Easy', 'Diff')
157 ('Easy', 'Diff')
158 ('Easy', 'Diff')
159 ('Easy', 'Diff')
160 ('Easy', 'Diff')
161 ('Easy', 'Diff')
162 ('Easy', 'Diff')
163 ('Easy', 'Diff')
164 ('Easy', 'Diff')
165 ('Easy', 'Diff')
166 ('Easy', 'Diff')
168 ('Easy', 'Diff')
169 ('Easy', 'Diff')
170 ('Total', 'Diff')
171 ('Easy', 'Diff')
172 ('Easy', 'Diff')
173 ('Easy', 'Diff')
174 ('Easy', 'Diff')
175 ('Easy', 'Diff')
176 ('Easy', 'Diff')
177 ('Easy', 'Diff')
178 ('Easy', 'Diff')
179 ('Easy', 'Diff')
180 ('Easy', 'Diff')
181 ('Easy', 'Diff')
182 ('Easy', 'Diff')
183 ('Total', 'Diff')
184 ('Easy', 'Diff')
185 ('Easy', 'Diff')
186 ('Total', 'Diff')
187 ('Easy', 'Diff')
188 ('Total', 'Diff')
189 ('Easy', 'Diff')
190 ('Easy', 'Diff')
191 ('Easy', 'Diff')
192 ('Easy', 'Diff')
193 ('Easy', 'Diff')
194 ('Easy', 'Diff')
196 ('Easy', 'Diff')
197 ('Easy', 'Diff')
198 ('Easy', 'Diff')
199 ('Easy', 'Diff')
200 ('All', 'Same')
201 ('Easy', 'Diff')
202 ('Easy', 'Diff')
203 ('Total', 'Diff')
204 ('Easy', 'Diff')
205 ('Easy', 'Diff')
206 ('Easy', 'Diff')
207 ('Easy', 'Diff')
208 ('Easy', 'Diff')
209 ('Easy', 'Diff')
210 ('Solid', 'Diff')
211 ('Easy', 'Diff')
212 ('Easy', 'Diff')
213 ('All', 'Same')
214 ('Easy', 'Diff')
215 ('Solid', 'Diff')
216 ('Easy', 'Diff')
217 ('Easy', 'Diff')
218 ('Total', 'Diff')
219 ('Easy', 'Diff')
220 ('Easy', 'Diff')
221 ('Easy', 'Diff')
222 ('Easy', 'Diff')
223 ('Easy', 'Diff')
224 ('Easy', 'Diff')
225 ('Total', 'Diff')
226 ('Easy', 'Diff')
227 ('Easy', 'Diff')
228 ('Easy', 'Diff')
229 ('Total', 'Diff')
230 ('Easy', 'Diff')
231 ('Easy', 'Diff')
232 ('Easy', 'Diff')
233 ('Easy', 'Diff')
234 ('Easy', 'Diff')
235 ('Easy', 'Diff')
236 ('Easy', 'Diff')
237 ('Easy', 'Diff')
238 ('Easy', 'Diff')
239 ('Easy', 'Diff')
240 ('Total', 'Diff')
241 ('Easy', 'Diff')
242 ('Easy', 'Diff')
243 ('Easy', 'Diff')
244 ('Easy', 'Diff')
245 ('Easy', 'Diff')
246 ('Easy', 'Diff')
247 ('Easy', 'Diff')
248 ('Easy', 'Diff')
249 ('Easy', 'Diff')
250 ('Easy', 'Diff')
251 ('Easy', 'Diff')
252 ('Easy', 'Diff')
253 ('Easy', 'Diff')
254 ('Easy', 'Diff')
255 ('Easy', 'Diff')
256 ('Easy', 'Diff')
257 ('Solid', 'Diff')
258 ('Easy', 'Diff')
259 ('Easy', 'Diff')
260 ('Easy', 'Diff')
261 ('Easy', 'Diff')
262 ('Easy', 'Diff')
263 ('Easy', 'Diff')
264 ('Easy', 'Diff')
265 ('Total', 'Diff')
266 ('Easy', 'Diff')
267 ('Easy', 'Diff')
268 ('Easy', 'Diff')
269 ('Easy', 'Diff')
270 ('Easy', 'Diff')
271 ('Easy', 'Diff')
272 ('Easy', 'Diff')
273 ('Easy', 'Diff')
274 ('Easy', 'Diff')
275 ('Easy', 'Diff')
276 ('Easy', 'Diff')
277 ('Easy', 'Diff')
278 ('Easy', 'Diff')
279 ('Easy', 'Diff')
280 ('Easy', 'Diff')
281 ('Easy', 'Diff')
282 ('Easy', 'Diff')
283 ('Easy', 'Diff')
284 ('Total', 'Diff')
285 ('Total', 'Diff')
286 ('Easy', 'Diff')
287 ('Easy', 'Diff')
288 ('Easy', 'Diff')
289 ('Easy', 'Diff')
290 ('Easy', 'Diff')
291 ('Easy', 'Diff')
292 ('Easy', 'Diff')
293 ('Easy', 'Diff')
294 ('Easy', 'Diff')
295 ('Easy', 'Diff')
296 ('Easy', 'Diff')
297 ('Easy', 'Diff')
298 ('Easy', 'Diff')
299 ('Easy', 'Diff')
300 ('Easy', 'Diff')
301 ('Easy', 'Diff')
302 ('Easy', 'Diff')
303 ('Easy', 'Diff')
304 ('Easy', 'Diff')
305 ('Easy', 'Diff')
306 ('Easy', 'Diff')
307 ('Easy', 'Diff')
308 ('Easy', 'Diff')
309 ('Easy', 'Diff')
310 ('Easy', 'Diff')
311 ('Easy', 'Diff')
312 ('Total', 'Diff')
313 ('Total', 'Diff')
314 ('Easy', 'Diff')
315 ('Solid', 'Diff')
316 ('Easy', 'Diff')
317 ('Easy', 'Diff')
318 ('Easy', 'Diff')
319 ('Easy', 'Diff')
320 ('Easy', 'Diff')
321 ('Easy', 'Diff')
322 ('Easy', 'Diff')
323 ('Easy', 'Diff')
324 ('Easy', 'Diff')
325 ('Easy', 'Diff')
326 ('Easy', 'Diff')
327 ('Easy', 'Diff')
328 ('Easy', 'Diff')
329 ('Easy', 'Diff')
330 ('Easy', 'Diff')
331 ('Easy', 'Diff')
332 ('Easy', 'Diff')
333 ('Easy', 'Diff')
334 ('Easy', 'Diff')
335 ('Easy', 'Diff')
336 ('Easy', 'Diff')
337 ('Solid', 'Diff')
338 ('Easy', 'Diff')
339 ('Easy', 'Diff')
340 ('Easy', 'Diff')
341 ('Easy', 'Diff')
342 ('Solid', 'Diff')
343 ('Easy', 'Diff')
344 ('Solid', 'Diff')
345 ('Easy', 'Diff')
346 ('Total', 'Diff')
347 ('Solid', 'Diff')
348 ('Easy', 'Diff')
349 ('Easy', 'Diff')
350 ('Easy', 'Diff')
351 ('Easy', 'Diff')
352 ('Easy', 'Diff')
353 ('Easy', 'Diff')
354 ('Easy', 'Diff')
355 ('Easy', 'Diff')
356 ('Total', 'Diff')
357 ('Easy', 'Diff')
358 ('Total', 'Diff')
359 ('Easy', 'Diff')
360 ('Total', 'Diff')
361 ('Easy', 'Diff')
362 ('Easy', 'Diff')
363 ('Easy', 'Diff')
364 ('Easy', 'Diff')
365 ('Total', 'Diff')
366 ('Easy', 'Diff')
367 ('Total', 'Diff')
368 ('Total', 'Diff')
369 ('Easy', 'Diff')
370 ('Total', 'Diff')
371 ('Easy', 'Diff')
372 ('Total', 'Diff')
373 ('Total', 'Diff')
374 ('Easy', 'Diff')
375 ('Easy', 'Diff')
376 ('Easy', 'Diff')
377 ('Easy', 'Diff')
378 ('Easy', 'Diff')
379 ('Easy', 'Diff')
380 ('Easy', 'Diff')
381 ('Easy', 'Diff')
382 ('Easy', 'Diff')
383 ('Easy', 'Diff')
384 ('Easy', 'Diff')
385 ('Easy', 'Diff')
386 ('Easy', 'Diff')
387 ('Easy', 'Diff')
388 ('Easy', 'Diff')
389 ('Easy', 'Diff')
390 ('Total', 'Diff')
391 ('Easy', 'Diff')
392 ('Easy', 'Diff')
393 ('Easy', 'Diff')
394 ('Easy', 'Diff')
395 ('Total', 'Diff')
396 ('Easy', 'Diff')
397 ('Easy', 'Diff')
398 ('Easy', 'Diff')
399 ('Total', 'Diff')
400 ('Total', 'Diff')
401 ('Easy', 'Diff')
402 ('Easy', 'Diff')
403 ('Easy', 'Diff')
404 ('Easy', 'Diff')
405 ('Easy', 'Diff')
406 ('Easy', 'Diff')
407 ('Easy', 'Diff')
408 ('Easy', 'Diff')
409 ('Easy', 'Diff')
410 ('Easy', 'Diff')
411 ('Easy', 'Diff')
412 ('Easy', 'Diff')
413 ('Easy', 'Diff')
414 ('Total', 'Diff')
415 ('Easy', 'Diff')
416 ('Easy', 'Diff')
417 ('Easy', 'Diff')
418 ('Easy', 'Diff')
419 ('Easy', 'Diff')
420 ('Easy', 'Diff')
421 ('Easy', 'Diff')
422 ('Easy', 'Diff')
423 ('Easy', 'Diff')
424 ('Easy', 'Diff')
425 ('Easy', 'Diff')
426 ('Easy', 'Diff')
427 ('Easy', 'Diff')
428 ('Easy', 'Diff')
429 ('Total', 'Diff')
430 ('Easy', 'Diff')
431 ('Easy', 'Diff')
432 ('Easy', 'Diff')
433 ('Easy', 'Diff')
434 ('Easy', 'Diff')
435 ('Solid', 'Diff')
436 ('Easy', 'Diff')
437 ('Easy', 'Diff')
438 ('Easy', 'Diff')
439 ('Easy', 'Diff')
440 ('Total', 'Diff')
441 ('Easy', 'Diff')
442 ('Easy', 'Diff')
443 ('Easy', 'Diff')
444 ('Total', 'Diff')
445 ('Easy', 'Diff')
446 ('Total', 'Diff')
447 ('Total', 'Diff')
448 ('Easy', 'Diff')
449 ('Easy', 'Diff')
450 ('Easy', 'Diff')
451 ('Solid', 'Diff')
452 ('Easy', 'Diff')
453 ('Easy', 'Diff')
454 ('Total', 'Diff')
455 ('Easy', 'Diff')
456 ('Easy', 'Diff')
457 ('Easy', 'Diff')
458 ('Easy', 'Diff')
459 ('Easy', 'Diff')
460 ('Easy', 'Diff')
461 ('Easy', 'Diff')
462 ('Easy', 'Diff')
463 ('Easy', 'Diff')
464 ('Easy', 'Diff')
465 ('Solid', 'Diff')
466 ('Easy', 'Diff')
467 ('Total', 'Diff')
468 ('Easy', 'Diff')
469 ('Easy', 'Diff')
470 ('Easy', 'Diff')
471 ('Easy', 'Diff')
472 ('Easy', 'Diff')
473 ('Easy', 'Diff')
474 ('Easy', 'Diff')
475 ('Easy', 'Diff')
476 ('Easy', 'Diff')
477 ('Easy', 'Diff')
478 ('Easy', 'Diff')
479 ('Solid', 'Diff')
480 ('Easy', 'Diff')
481 ('Solid', 'Diff')
482 ('Total', 'Diff')
483 ('Easy', 'Diff')
484 ('Easy', 'Diff')
485 ('Solid', 'Diff')
486 ('Total', 'Diff')
487 ('Easy', 'Diff')
488 ('Easy', 'Diff')
489 ('Easy', 'Diff')
490 ('Easy', 'Diff')
491 ('Easy', 'Diff')
492 ('Total', 'Diff')
493 ('Easy', 'Diff')
494 ('Easy', 'Diff')
495 ('Total', 'Diff')
496 ('Easy', 'Diff')
497 ('Easy', 'Diff')
498 ('Easy', 'Diff')
499 ('Total', 'Diff')
500 ('Easy', 'Diff')
501 ('Easy', 'Diff')
502 ('Easy', 'Diff')
503 ('Easy', 'Diff')
504 ('Easy', 'Diff')
505 ('Easy', 'Diff')
506 ('Easy', 'Diff')
507 ('Easy', 'Diff')
508 ('Easy', 'Diff')
509 ('Total', 'Diff')
510 ('Easy', 'Diff')
511 ('Easy', 'Diff')
512 ('Easy', 'Diff')
513 ('Easy', 'Diff')
514 ('Easy', 'Diff')
515 ('Easy', 'Diff')
516 ('Easy', 'Diff')
517 ('Easy', 'Diff')
518 ('All', 'Same')
520 ('Easy', 'Diff')
521 ('Total', 'Diff')
522 ('Easy', 'Diff')
523 ('Easy', 'Diff')
524 ('Easy', 'Diff')
525 ('Easy', 'Diff')
526 ('Easy', 'Diff')
527 ('Easy', 'Diff')
528 ('Easy', 'Diff')
529 ('Total', 'Diff')
530 ('Easy', 'Diff')
531 ('Easy', 'Diff')
532 ('Easy', 'Diff')
533 ('Easy', 'Diff')
534 ('All', 'Same')
535 ('Easy', 'Diff')
536 ('Solid', 'Diff')
537 ('Easy', 'Diff')
539 ('Easy', 'Diff')
540 ('Easy', 'Diff')
541 ('Solid', 'Diff')
542 ('Easy', 'Diff')
543 ('Easy', 'Diff')
544 ('Easy', 'Diff')
545 ('Total', 'Diff')
546 ('Easy', 'Diff')
547 ('Easy', 'Diff')
548 ('Easy', 'Diff')
549 ('Easy', 'Diff')
550 ('Easy', 'Diff')
551 ('Easy', 'Diff')
552 ('Easy', 'Diff')
553 ('Easy', 'Diff')
554 ('Easy', 'Diff')
555 ('Easy', 'Diff')
556 ('Easy', 'Diff')
557 ('Easy', 'Diff')
558 ('Easy', 'Diff')
559 ('Easy', 'Diff')
560 ('Easy', 'Diff')
561 ('Easy', 'Diff')
562 ('Easy', 'Diff')
563 ('Total', 'Diff')
564 ('Total', 'Diff')
565 ('Easy', 'Diff')
566 ('Total', 'Diff')
567 ('Easy', 'Diff')
568 ('Total', 'Diff')
569 ('Easy', 'Diff')
570 ('Easy', 'Diff')
571 ('Easy', 'Diff')
572 ('Easy', 'Diff')
573 ('Easy', 'Diff')
574 ('Easy', 'Diff')
575 ('Total', 'Diff')
576 ('Easy', 'Diff')
577 ('Easy', 'Diff')
578 ('Easy', 'Diff')
579 ('Easy', 'Diff')
580 ('Total', 'Diff')
582 ('Easy', 'Diff')
583 ('Easy', 'Diff')
584 ('Easy', 'Diff')
585 ('Easy', 'Diff')
586 ('Easy', 'Diff')
587 ('Easy', 'Diff')
588 ('Easy', 'Diff')
589 ('Easy', 'Diff')
590 ('Easy', 'Diff')
591 ('Easy', 'Diff')
592 ('Easy', 'Diff')
593 ('Total', 'Diff')
594 ('Easy', 'Diff')
595 ('Easy', 'Diff')
596 ('Easy', 'Diff')
597 ('Easy', 'Diff')
598 ('Easy', 'Diff')
599 ('Easy', 'Diff')
600 ('Easy', 'Diff')
601 ('Easy', 'Diff')
602 ('Total', 'Diff')
603 ('Total', 'Diff')
604 ('Easy', 'Diff')
605 ('Easy', 'Diff')
606 ('Easy', 'Diff')
607 ('Easy', 'Diff')
608 ('Easy', 'Diff')
609 ('Easy', 'Diff')
610 ('Total', 'Diff')
611 ('Easy', 'Diff')
612 ('Easy', 'Diff')
613 ('Easy', 'Diff')
614 ('Total', 'Diff')
615 ('Easy', 'Diff')
616 ('All', 'Same')
617 ('Easy', 'Diff')
618 ('Easy', 'Diff')
619 ('Easy', 'Diff')
621 ('Easy', 'Diff')
622 ('Easy', 'Diff')
623 ('Easy', 'Diff')
624 ('Total', 'Diff')
625 ('Easy', 'Diff')
626 ('Easy', 'Diff')
627 ('Easy', 'Diff')
628 ('Easy', 'Diff')
629 ('Easy', 'Diff')
630 ('Easy', 'Diff')
631 ('Total', 'Diff')
632 ('Easy', 'Diff')
633 ('Easy', 'Diff')
634 ('Total', 'Diff')
635 ('Easy', 'Diff')
636 ('Easy', 'Diff')
637 ('Easy', 'Diff')
638 ('Easy', 'Diff')
639 ('Easy', 'Diff')
640 ('Easy', 'Diff')
641 ('Easy', 'Diff')
642 ('Solid', 'Diff')
643 ('Easy', 'Diff')
645 ('Easy', 'Diff')
646 ('Easy', 'Diff')
647 ('Easy', 'Diff')
648 ('Easy', 'Diff')
649 ('All', 'Same')
650 ('Easy', 'Diff')
651 ('Easy', 'Diff')
652 ('Easy', 'Diff')
653 ('Easy', 'Diff')
654 ('Total', 'Diff')
655 ('Easy', 'Diff')
656 ('Easy', 'Diff')
657 ('Easy', 'Diff')
658 ('Easy', 'Diff')
659 ('Easy', 'Diff')
660 ('Easy', 'Diff')
661 ('Easy', 'Diff')
662 ('Easy', 'Diff')
663 ('Easy', 'Diff')
664 ('Easy', 'Diff')
665 ('Easy', 'Diff')
666 ('Easy', 'Diff')
667 ('Easy', 'Diff')
668 ('Easy', 'Diff')
669 ('Easy', 'Diff')
670 ('Easy', 'Diff')
671 ('Easy', 'Diff')
672 ('Easy', 'Diff')
673 ('Easy', 'Diff')
674 ('Easy', 'Diff')
675 ('Easy', 'Diff')
676 ('Easy', 'Diff')
677 ('Easy', 'Diff')
678 ('Easy', 'Diff')
679 ('Easy', 'Diff')
680 ('Easy', 'Diff')
681 ('Easy', 'Diff')
682 ('Easy', 'Diff')
683 ('Easy', 'Diff')
684 ('Total', 'Diff')
685 ('Easy', 'Diff')
686 ('Easy', 'Diff')
687 ('Easy', 'Diff')
688 ('Easy', 'Diff')
689 ('Easy', 'Diff')
690 ('Easy', 'Diff')
692 ('Easy', 'Diff')
693 ('Easy', 'Diff')
694 ('Easy', 'Diff')
695 ('Solid', 'Diff')
696 ('Easy', 'Diff')
697 ('Easy', 'Diff')
698 ('Easy', 'Diff')
699 ('Easy', 'Diff')
700 ('Easy', 'Diff')
701 ('Easy', 'Diff')
702 ('Easy', 'Diff')
703 ('Easy', 'Diff')
704 ('Easy', 'Diff')
705 ('Easy', 'Diff')
706 ('Total', 'Diff')
707 ('Easy', 'Diff')
708 ('Easy', 'Diff')
709 ('Easy', 'Diff')
710 ('Easy', 'Diff')
711 ('Solid', 'Diff')
712 ('Easy', 'Diff')
713 ('Easy', 'Diff')
714 ('Easy', 'Diff')
715 ('Easy', 'Diff')
716 ('Total', 'Diff')
717 ('Easy', 'Diff')
718 ('Easy', 'Diff')
719 ('Easy', 'Diff')
720 ('Easy', 'Diff')
722 ('Total', 'Diff')
723 ('Easy', 'Diff')
725 ('Easy', 'Diff')
726 ('Total', 'Diff')
727 ('Total', 'Diff')
728 ('Easy', 'Diff')
729 ('Easy', 'Diff')
730 ('Easy', 'Diff')
731 ('Easy', 'Diff')
732 ('Easy', 'Diff')
733 ('Easy', 'Diff')
734 ('Easy', 'Diff')
735 ('Easy', 'Diff')
736 ('Easy', 'Diff')
737 ('Easy', 'Diff')
738 ('Easy', 'Diff')
739 ('Easy', 'Diff')
740 ('Easy', 'Diff')
741 ('Easy', 'Diff')
742 ('Solid', 'Diff')
743 ('Easy', 'Diff')
744 ('Easy', 'Diff')
745 ('Easy', 'Diff')
746 ('Total', 'Diff')
747 ('Easy', 'Diff')
748 ('Easy', 'Diff')
749 ('Easy', 'Diff')
750 ('Easy', 'Diff')
751 ('Total', 'Diff')
752 ('Easy', 'Diff')
753 ('Total', 'Diff')
754 ('Easy', 'Diff')
755 ('Easy', 'Diff')
756 ('Solid', 'Diff')
757 ('Easy', 'Diff')
758 ('Easy', 'Diff')
759 ('Easy', 'Diff')
760 ('Easy', 'Diff')
761 ('Easy', 'Diff')
762 ('Easy', 'Diff')
763 ('Easy', 'Diff')
764 ('Easy', 'Diff')
765 ('Easy', 'Diff')
766 ('Easy', 'Diff')
767 ('Easy', 'Diff')
768 ('Easy', 'Diff')
769 ('Easy', 'Diff')
770 ('Easy', 'Diff')
771 ('Total', 'Diff')
772 ('Easy', 'Diff')
773 ('Easy', 'Diff')
774 ('Total', 'Diff')
775 ('Easy', 'Diff')
776 ('Easy', 'Diff')
777 ('Easy', 'Diff')
778 ('Easy', 'Diff')
779 ('Easy', 'Diff')
780 ('Easy', 'Diff')
781 ('Easy', 'Diff')
782 ('Easy', 'Diff')
783 ('Easy', 'Diff')
784 ('Solid', 'Diff')
785 ('Easy', 'Diff')
786 ('Easy', 'Diff')
787 ('Easy', 'Diff')
788 ('Easy', 'Diff')
789 ('Total', 'Diff')
790 ('Easy', 'Diff')
791 ('Easy', 'Diff')
792 ('Easy', 'Diff')
793 ('Easy', 'Diff')
794 ('Easy', 'Diff')
795 ('Easy', 'Diff')
796 ('Easy', 'Diff')
797 ('Total', 'Diff')
798 ('Easy', 'Diff')
799 ('Easy', 'Diff')
800 ('Easy', 'Diff')
801 ('Easy', 'Diff')
802 ('Easy', 'Diff')
803 ('Easy', 'Diff')
804 ('Easy', 'Diff')
805 ('Easy', 'Diff')
806 ('Easy', 'Diff')
807 ('Easy', 'Diff')
808 ('Easy', 'Diff')
809 ('Easy', 'Diff')
810 ('Easy', 'Diff')
811 ('Easy', 'Diff')
812 ('Easy', 'Diff')
814 ('Total', 'Diff')
815 ('Easy', 'Diff')
816 ('Easy', 'Diff')
817 ('Easy', 'Diff')
818 ('Easy', 'Diff')
819 ('Easy', 'Diff')
821 ('Easy', 'Diff')
822 ('Easy', 'Diff')
823 ('Easy', 'Diff')
824 ('Easy', 'Diff')
825 ('Easy', 'Diff')
826 ('Easy', 'Diff')
827 ('Easy', 'Diff')
828 ('Easy', 'Diff')
829 ('Total', 'Diff')
830 ('Total', 'Diff')
831 ('Easy', 'Diff')
832 ('Easy', 'Diff')
833 ('Easy', 'Diff')
834 ('Easy', 'Diff')
835 ('Easy', 'Diff')
836 ('Easy', 'Diff')
837 ('Easy', 'Diff')
838 ('Easy', 'Diff')
839 ('Solid', 'Diff')
840 ('Easy', 'Diff')
841 ('Easy', 'Diff')
842 ('Easy', 'Diff')
843 ('Easy', 'Diff')
844 ('Easy', 'Diff')
845 ('Solid', 'Diff')
846 ('Easy', 'Diff')
847 ('Easy', 'Diff')
848 ('Total', 'Diff')
849 ('Easy', 'Diff')
850 ('Easy', 'Diff')
851 ('Easy', 'Diff')
852 ('Easy', 'Diff')
853 ('Easy', 'Diff')
854 ('Easy', 'Diff')
855 ('Solid', 'Diff')
856 ('Easy', 'Diff')
857 ('Easy', 'Diff')
858 ('Easy', 'Diff')
859 ('Easy', 'Diff')
860 ('Easy', 'Diff')
861 ('Easy', 'Diff')
862 ('Easy', 'Diff')
863 ('All', 'Same')
864 ('Easy', 'Diff')
865 ('Easy', 'Diff')
866 ('Easy', 'Diff')
867 ('Easy', 'Diff')
868 ('Total', 'Diff')
869 ('Easy', 'Diff')
870 ('Easy', 'Diff')
871 ('Total', 'Diff')
872 ('Easy', 'Diff')
873 ('Easy', 'Diff')
874 ('Easy', 'Diff')
875 ('Easy', 'Diff')
876 ('Total', 'Diff')
877 ('Easy', 'Diff')
878 ('Easy', 'Diff')
879 ('Easy', 'Diff')
880 ('Total', 'Diff')
881 ('Solid', 'Diff')
882 ('Easy', 'Diff')
883 ('Easy', 'Diff')
884 ('Easy', 'Diff')
885 ('Total', 'Diff')
886 ('Easy', 'Diff')
887 ('Easy', 'Diff')
888 ('Total', 'Diff')
889 ('Easy', 'Diff')
890 ('Easy', 'Diff')
891 ('Easy', 'Diff')
892 ('Easy', 'Diff')
893 ('Easy', 'Diff')
894 ('Easy', 'Diff')
895 ('Easy', 'Diff')
896 ('Easy', 'Diff')
897 ('Easy', 'Diff')
898 ('Easy', 'Diff')
899 ('Solid', 'Diff')
900 ('All', 'Same')
901 ('Easy', 'Diff')
902 ('Easy', 'Diff')
905 ('Easy', 'Diff')
906 ('Total', 'Diff')
907 ('Easy', 'Diff')
908 ('Easy', 'Diff')
909 ('Easy', 'Diff')
910 ('Easy', 'Diff')
911 ('Solid', 'Diff')
912 ('Easy', 'Diff')
913 ('Solid', 'Diff')
914 ('Easy', 'Diff')
915 ('Easy', 'Diff')
916 ('Easy', 'Diff')
917 ('Total', 'Diff')
918 ('Easy', 'Diff')
920 ('Easy', 'Diff')
921 ('Easy', 'Diff')
922 ('Easy', 'Diff')
923 ('Easy', 'Diff')
924 ('Easy', 'Diff')
925 ('Total', 'Diff')
926 ('Total', 'Diff')
928 ('Easy', 'Diff')
929 ('Easy', 'Diff')
930 ('Easy', 'Diff')
931 ('Easy', 'Diff')
932 ('Easy', 'Diff')
933 ('Easy', 'Diff')
934 ('Easy', 'Diff')
935 ('Easy', 'Diff')
936 ('Easy', 'Diff')
937 ('Easy', 'Diff')
938 ('Easy', 'Diff')
939 ('Easy', 'Diff')
940 ('Easy', 'Diff')
941 ('Solid', 'Diff')
942 ('Easy', 'Diff')
943 ('Easy', 'Diff')
944 ('Total', 'Diff')
945 ('Easy', 'Diff')
946 ('Easy', 'Diff')
947 ('Easy', 'Diff')
949 ('Easy', 'Diff')
950 ('Easy', 'Diff')
951 ('Easy', 'Diff')
952 ('Total', 'Diff')
953 ('Easy', 'Diff')
954 ('Easy', 'Diff')
955 ('Easy', 'Diff')
956 ('Easy', 'Diff')
957 ('Easy', 'Diff')
958 ('Total', 'Diff')
959 ('Total', 'Diff')
960 ('Easy', 'Diff')
961 ('Easy', 'Diff')
962 ('Easy', 'Diff')
963 ('Easy', 'Diff')
964 ('Easy', 'Diff')
965 ('Easy', 'Diff')
966 ('Easy', 'Diff')
968 ('Easy', 'Diff')
969 ('Easy', 'Diff')

In [28]:
df_result_neg_cluster.to_csv("./chexpert_mismatches_swap_cluster.csv")

In [45]:
for item in df_result_neg_cluster["report"]:
    if (item in df_neg["report"]) or (item in df_pos["report"]):
        print("Bad!!!")